import Foundation
import XCTest
import ZIPFoundation
@testable import UpdaterPlugin

final class ZipUtilsTests: XCTestCase {
  private struct EntrySpec {
    let path: String
    let type: Entry.EntryType
    let data: Data

    init(_ path: String, type: Entry.EntryType = .file, contents: String = "fixture") {
      self.path = path
      self.type = type
      data = Data(contents.utf8)
    }
  }

  private struct Fixture {
    let root: URL
    let archive: URL
    let destination: URL

    func cleanup() {
      try? FileManager.default.removeItem(at: root)
    }
  }

  func testExtractsYazlArchiveWithAdjacentDotsInsideFilename() throws {
    // Generated by @otakit/cli's yazl 2.5.1 writer. Both entries use ZIP data
    // descriptors, matching the archive shape reported in OtaKit issue #15.
    let archiveData = try XCTUnwrap(Data(
      base64Encoded: """
        UEsDBBQACAgIAMSuG10AAAAAAAAAAAAAAAAKAAAAaW5kZXguaHRtbLNRTMlPLqksSFXI
        KMnNsbMpySzJSbUrSi0oyrfRh3AAUEsHCFi8GEAgAAAAIwAAAFBLAwQUAAgICADE
        rhtdAAAAAAAAAAAAAAAADgAAAHNhZmUuLmNodW5rLmpzS87PK87PSdXLyU/XUCpO
        TEtV0gQAUEsHCJNQbzkVAAAAEwAAAFBLAQI/AxQACAgIAMSuG11YvBhAIAAAACMA
        AAAKAAAAAAAAAAAAAACkgQAAAABpbmRleC5odG1sUEsBAj8DFAAICAgAxK4bXZNQ
        bzkVAAAAEwAAAA4AAAAAAAAAAAAAAKSBWAAAAHNhZmUuLmNodW5rLmpzUEsFBgAA
        AAACAAIAdAAAAKkAAAAAAA==
        """,
      options: .ignoreUnknownCharacters
    ))
    XCTAssertEqual(archiveData[6] & 0x08, 0x08, "Fixture must retain yazl's data descriptor flag")
    let fixture = try makeFixture(archiveData: archiveData)
    defer { fixture.cleanup() }

    try ZipUtils().extractSecurely(zipURL: fixture.archive, to: fixture.destination)

    XCTAssertEqual(
      try String(
        contentsOf: fixture.destination.appendingPathComponent("safe..chunk.js"),
        encoding: .utf8
      ),
      "console.log(\"safe\")"
    )
    XCTAssertTrue(
      FileManager.default.fileExists(
        atPath: fixture.destination.appendingPathComponent("index.html").path
      )
    )
  }

  func testParentDirectoryCheckUsesPathComponentsNotSubstrings() {
    let safePaths = [
      "asset..js",
      "...",
      ".well-known/config.json",
      "dir/..hidden/file.js",
      "dir/name...js",
      "dir/%2E%2E/file.js"
    ]
    for path in safePaths {
      XCTAssertFalse(
        ZipUtils.containsParentDirectoryComponent(in: path),
        "Expected safe path: \(path)"
      )
    }

    let unsafePaths = [
      "..",
      "../escape.js",
      "dir/../escape.js",
      "dir/..",
      "/../escape.js",
      "dir//../escape.js"
    ]
    for path in unsafePaths {
      XCTAssertTrue(
        ZipUtils.containsParentDirectoryComponent(in: path),
        "Expected parent-directory path component: \(path)"
      )
    }
  }

  func testExtractsNestedUnicodeAndDotNamedFiles() throws {
    let fixture = try makeFixture(entries: [
      EntrySpec("index.html", contents: "home"),
      EntrySpec("assets/.well-known/name...üñícode.js", contents: "payload"),
      EntrySpec("assets/empty.txt", contents: "")
    ])
    defer { fixture.cleanup() }

    try ZipUtils().extractSecurely(zipURL: fixture.archive, to: fixture.destination)

    XCTAssertEqual(
      try String(
        contentsOf: fixture.destination
          .appendingPathComponent("assets/.well-known/name...üñícode.js"),
        encoding: .utf8
      ),
      "payload"
    )
    XCTAssertEqual(
      try Data(contentsOf: fixture.destination.appendingPathComponent("assets/empty.txt")),
      Data()
    )
  }

  func testRejectsExactParentDirectorySegmentBeforeExtractingAnything() throws {
    let fixture = try makeFixture(entries: [
      EntrySpec("index.html", contents: "must not be written"),
      EntrySpec("assets/../escape.js")
    ])
    defer { fixture.cleanup() }

    XCTAssertThrowsError(
      try ZipUtils().extractSecurely(zipURL: fixture.archive, to: fixture.destination)
    ) { error in
      guard case let ZipUtilsError.pathTraversal(path) = error else {
        return XCTFail("Expected pathTraversal, got \(String(reflecting: error))")
      }
      XCTAssertEqual(path, "assets/../escape.js")
      XCTAssertEqual(
        error.localizedDescription,
        "ZIP entry contains a parent-directory path component: assets/../escape.js"
      )
    }
    XCTAssertFalse(FileManager.default.fileExists(atPath: fixture.destination.path))
  }

  func testRejectsAbsolutePathBeforeExtractingAnything() throws {
    let fixture = try makeFixture(entries: [EntrySpec("/escape.js")])
    defer { fixture.cleanup() }

    XCTAssertThrowsError(
      try ZipUtils().extractSecurely(zipURL: fixture.archive, to: fixture.destination)
    ) { error in
      guard case let ZipUtilsError.absolutePath(path) = error else {
        return XCTFail("Expected absolutePath, got \(String(reflecting: error))")
      }
      XCTAssertEqual(path, "/escape.js")
    }
    XCTAssertFalse(FileManager.default.fileExists(atPath: fixture.destination.path))
  }

  func testRejectsSymbolicLinkBeforeExtractingAnything() throws {
    let fixture = try makeFixture(entries: [
      EntrySpec("index.html", contents: "must not be written"),
      EntrySpec("link", type: .symlink, contents: "../outside")
    ])
    defer { fixture.cleanup() }

    XCTAssertThrowsError(
      try ZipUtils().extractSecurely(zipURL: fixture.archive, to: fixture.destination)
    ) { error in
      guard case let ZipUtilsError.symlinkNotAllowed(path) = error else {
        return XCTFail("Expected symlinkNotAllowed, got \(String(reflecting: error))")
      }
      XCTAssertEqual(path, "link")
    }
    XCTAssertFalse(FileManager.default.fileExists(atPath: fixture.destination.path))
  }

  func testRejectsUnreadableArchiveWithClearError() throws {
    let fixture = try makeFixture(archiveData: Data("not a zip".utf8))
    defer { fixture.cleanup() }

    XCTAssertThrowsError(
      try ZipUtils().extractSecurely(zipURL: fixture.archive, to: fixture.destination)
    ) { error in
      guard case ZipUtilsError.invalidZip = error else {
        return XCTFail("Expected invalidZip, got \(String(reflecting: error))")
      }
      XCTAssertEqual(
        error.localizedDescription,
        "Downloaded bundle is not a readable ZIP archive"
      )
    }
    XCTAssertFalse(FileManager.default.fileExists(atPath: fixture.destination.path))
  }

  private func makeFixture(archiveData: Data) throws -> Fixture {
    let fixture = try emptyFixture()
    try archiveData.write(to: fixture.archive)
    return fixture
  }

  private func makeFixture(entries: [EntrySpec]) throws -> Fixture {
    let fixture = try emptyFixture()
    let archive = try Archive(url: fixture.archive, accessMode: .create, pathEncoding: nil)
    for entry in entries {
      try archive.addEntry(
        with: entry.path,
        type: entry.type,
        uncompressedSize: Int64(entry.data.count),
        compressionMethod: entry.type == .file ? .deflate : .none
      ) { position, size in
        let lowerBound = Int(position)
        let upperBound = min(lowerBound + size, entry.data.count)
        return entry.data.subdata(in: lowerBound..<upperBound)
      }
    }
    return fixture
  }

  private func emptyFixture() throws -> Fixture {
    let root = FileManager.default.temporaryDirectory
      .appendingPathComponent("otakit-zip-tests-\(UUID().uuidString)", isDirectory: true)
    try FileManager.default.createDirectory(at: root, withIntermediateDirectories: true)
    return Fixture(
      root: root,
      archive: root.appendingPathComponent("fixture.zip"),
      destination: root.appendingPathComponent("extracted", isDirectory: true)
    )
  }
}
