import type { Metadata } from 'next';

import { site } from '@/lib/site';

export type BlogPostMeta = {
  slug: string;
  title: string;
  /** Title used in <title> / OG. Defaults to `title` when omitted. */
  seoTitle?: string;
  description: string;
  category: 'Guides' | 'Comparison' | 'Compliance' | 'Migration' | 'Tutorial';
  publishedAt: string;
  updatedAt?: string;
  readingTime: string;
  keywords: string[];
  order: number;
  featured?: boolean;
  relatedDocs: Array<{
    href: string;
    label: string;
  }>;
};

export const BLOG_POSTS: BlogPostMeta[] = [
  {
    slug: 'how-ota-works-for-capacitor-apps',
    title: 'How OTA updates work in Capacitor apps',
    seoTitle: 'How OTA Updates Work in Capacitor Apps',
    description:
      'What actually happens when a Capacitor app updates over the air: bundles, channels, signed manifests, delta downloads, safe activation, and automatic rollback.',
    category: 'Guides',
    publishedAt: '2026-07-02',
    readingTime: '9 min read',
    keywords: [
      'Capacitor OTA updates',
      'over-the-air updates',
      'Capacitor live updates',
      'how OTA works',
      'app update rollback',
      'update channels',
    ],
    order: 3,
    relatedDocs: [
      { href: '/docs/setup', label: 'Setup' },
      { href: '/docs/update-strategies', label: 'Update strategies' },
      { href: '/docs/security', label: 'Security' },
    ],
  },
  {
    slug: 'ota-policies-for-app-store-and-google-play',
    title: 'Are OTA updates allowed? App Store and Google Play rules, explained',
    seoTitle: 'Are OTA Updates Allowed? App Store & Google Play Rules Explained',
    description:
      'What Apple and Google actually say about over-the-air updates, quoted from the primary sources — and the practical line between compliant web-layer updates and rejection territory.',
    category: 'Compliance',
    publishedAt: '2026-07-02',
    readingTime: '9 min read',
    keywords: [
      'are OTA updates allowed',
      'App Store OTA policy',
      'Google Play OTA policy',
      'guideline 2.5.2',
      'Apple 3.3.1B interpreted code',
      'Capacitor app store compliance',
      'CodePush legal',
    ],
    order: 4,
    relatedDocs: [
      { href: '/docs/setup', label: 'Setup' },
      { href: '/docs/plugin', label: 'Plugin API' },
      { href: '/docs/security', label: 'Security' },
    ],
  },
  {
    slug: 'best-live-update-frameworks-for-capacitor-apps',
    title: 'The best live update tools for Capacitor apps in 2026',
    seoTitle: 'Best Live Update Tools for Capacitor Apps in 2026 (Compared)',
    description:
      'OtaKit vs Capgo vs Capawesome, compared honestly: pricing models, delta updates, encryption, rollback safety, and which one fits your Capacitor release process.',
    category: 'Comparison',
    publishedAt: '2026-07-02',
    readingTime: '10 min read',
    keywords: [
      'best Capacitor live update',
      'Capacitor OTA comparison',
      'OtaKit vs Capgo',
      'OtaKit vs Capawesome',
      'Capgo vs Capawesome',
      'CodePush alternative Capacitor',
    ],
    order: 5,
    relatedDocs: [
      { href: '/docs/channels', label: 'Channels & runtime version' },
      { href: '/docs/cli', label: 'CLI reference' },
      { href: '/docs/plugin', label: 'Plugin API' },
    ],
  },
  {
    slug: 'the-1-alternative-to-capgo-capawesome',
    title: 'Why OtaKit is the better, cheaper alternative to Capgo and Capawesome',
    seoTitle: 'The Better, Cheaper Alternative to Capgo and Capawesome (2026)',
    description:
      'OtaKit delivers the same live updates for a fraction of the price: no MAU metering, CDN-direct delivery, delta updates, end-to-end encryption, and a fully MIT-licensed stack.',
    category: 'Comparison',
    publishedAt: '2026-07-02',
    readingTime: '7 min read',
    keywords: [
      'Capgo alternative',
      'Capawesome alternative',
      'Capacitor live update pricing',
      'open source OTA updates',
      'self-hosted live updates',
    ],
    order: 6,
    relatedDocs: [
      { href: '/docs/setup', label: 'Setup' },
      { href: '/docs/channels', label: 'Channels & runtime version' },
      { href: '/docs/security', label: 'Security' },
    ],
  },
  {
    slug: 'capgo-alternative',
    title: 'The cheaper, better Capgo alternative for Capacitor live updates',
    seoTitle: 'Capgo Alternative: Cheaper, Better Live Updates for Capacitor (2026)',
    description:
      'Looking for a Capgo alternative? OtaKit ships the same live updates with no MAU or bandwidth metering — most apps pay $0–25/mo where Capgo charges $33–208+. Real price math inside.',
    category: 'Comparison',
    publishedAt: '2026-07-02',
    readingTime: '6 min read',
    keywords: [
      'Capgo alternative',
      'Capgo pricing',
      'Capgo vs OtaKit',
      'Capacitor live updates',
      'capacitor-updater alternative',
      'Capgo migration',
    ],
    order: 7,
    relatedDocs: [
      { href: '/docs/setup', label: 'Setup' },
      { href: '/docs/cli', label: 'CLI reference' },
      { href: '/docs/security', label: 'Security' },
    ],
  },
  {
    slug: 'capawesome-alternative',
    title: 'The cheaper, better Capawesome alternative for live updates',
    seoTitle: 'Capawesome Alternative: Cheaper, Better Live Updates for Capacitor (2026)',
    description:
      'Looking for a Capawesome Live Update alternative? OtaKit has no MAU caps, a fully open-source stack, and CDN-direct delivery — most apps pay $0–25/mo where Capawesome charges $29–249.',
    category: 'Comparison',
    publishedAt: '2026-07-02',
    readingTime: '6 min read',
    keywords: [
      'Capawesome alternative',
      'Capawesome Live Update pricing',
      'Capawesome vs OtaKit',
      'Capacitor live updates',
      'capacitor-live-update alternative',
    ],
    order: 8,
    relatedDocs: [
      { href: '/docs/setup', label: 'Setup' },
      { href: '/docs/update-strategies', label: 'Update strategies' },
      { href: '/docs/security', label: 'Security' },
    ],
  },
  {
    slug: 'vibe-code-an-app-from-your-mobile-with-claude-code-remote-and-otakit',
    title: 'Vibe code your app from your phone with Claude Code and OtaKit',
    seoTitle: 'Vibe Code an App From Your Phone With Claude Code + OTA Updates',
    description:
      'A real mobile-only dev loop: drive Claude Code from your phone, build in the cloud, and ship the result straight into your installed Capacitor app with an OTA update.',
    category: 'Guides',
    publishedAt: '2026-07-02',
    readingTime: '7 min read',
    keywords: [
      'Claude Code mobile',
      'vibe coding',
      'code from phone',
      'Capacitor OTA workflow',
      'Claude Code Capacitor',
      'ship app updates from phone',
    ],
    order: 1,
    featured: true,
    relatedDocs: [
      { href: '/docs/react', label: 'React guide' },
      { href: '/docs/guide', label: 'Next.js guide' },
      { href: '/docs/ci', label: 'CI automation' },
    ],
  },
  {
    slug: 'migrate-from-capgo-and-capawesome',
    title: 'How to migrate from Capgo or Capawesome to OtaKit',
    seoTitle: 'Migrate From Capgo or Capawesome to OtaKit: Complete Guide',
    description:
      'A production-grade migration guide: exact config and API translations from Capgo and Capawesome to OtaKit, what maps cleanly, and a safe cutover plan for your install base.',
    category: 'Migration',
    publishedAt: '2026-07-02',
    readingTime: '14 min read',
    keywords: [
      'migrate from Capgo',
      'migrate from Capawesome',
      'Capgo migration guide',
      'Capacitor updater migration',
      'switch OTA provider',
    ],
    order: 2,
    featured: true,
    relatedDocs: [
      { href: '/docs/setup', label: 'Setup' },
      { href: '/docs/cli', label: 'CLI reference' },
      { href: '/docs/update-strategies', label: 'Update strategies' },
    ],
  },
  {
    slug: 'nextjs-to-ios-android-with-capacitor',
    title: 'Convert your Next.js app to iOS and Android with Capacitor',
    seoTitle: 'Next.js to iOS & Android with Capacitor (+ Live Updates) 2026',
    description:
      'Turn an existing Next.js app into real iOS and Android apps with Capacitor — static export config, native project setup, plugins, safe areas — then ship JS/CSS changes instantly with OtaKit live updates.',
    category: 'Tutorial',
    publishedAt: '2026-07-08',
    readingTime: '11 min read',
    keywords: [
      'Next.js mobile app',
      'Next.js Capacitor',
      'Next.js iOS Android',
      'convert Next.js to mobile app',
      'Capacitor 8 Next.js',
      'Next.js live updates',
    ],
    order: 9,
    featured: true,
    relatedDocs: [
      { href: '/docs/guide', label: 'Next.js guide' },
      { href: '/docs/setup', label: 'Setup' },
      { href: '/docs/cli', label: 'CLI reference' },
    ],
  },
  {
    slug: 'react-to-ios-android-with-capacitor',
    title: 'Turn your React app into iOS and Android apps with Capacitor',
    seoTitle: 'React to iOS & Android with Capacitor (+ Live Updates) 2026',
    description:
      'A step-by-step guide to wrapping a plain React (Vite) app as native iOS and Android with Capacitor — no React Native rewrite — plus over-the-air updates with OtaKit so you can ship fixes without a store review.',
    category: 'Tutorial',
    publishedAt: '2026-07-08',
    readingTime: '10 min read',
    keywords: [
      'React mobile app',
      'React Capacitor',
      'React to native app',
      'Capacitor React tutorial',
      'React iOS Android',
      'React live updates',
    ],
    order: 10,
    relatedDocs: [
      { href: '/docs/react', label: 'React guide' },
      { href: '/docs/setup', label: 'Setup' },
      { href: '/docs/update-strategies', label: 'Update strategies' },
    ],
  },
  {
    slug: 'vue-to-ios-android-with-capacitor',
    title: 'Build iOS and Android apps from your Vue app with Capacitor',
    seoTitle: 'Vue to iOS & Android with Capacitor (+ Live Updates) 2026',
    description:
      'Convert a Vue 3 (Vite) web app into native iOS and Android apps with Capacitor, add device plugins, and wire up OtaKit live updates to push web-layer changes over the air in minutes.',
    category: 'Tutorial',
    publishedAt: '2026-07-08',
    readingTime: '10 min read',
    keywords: [
      'Vue mobile app',
      'Vue Capacitor',
      'Vue to native app',
      'Capacitor Vue tutorial',
      'Vue iOS Android',
      'Vue live updates',
    ],
    order: 11,
    relatedDocs: [
      { href: '/docs/setup', label: 'Setup' },
      { href: '/docs/cli', label: 'CLI reference' },
      { href: '/docs/update-strategies', label: 'Update strategies' },
    ],
  },
  {
    slug: 'capacitor-ota-update-security',
    title: 'How to secure Capacitor OTA updates',
    seoTitle: 'Capacitor OTA Update Security: A Practical Guide (2026)',
    description:
      'OTA updates ship code to production devices, so the pipeline is a security surface. How to sign bundles, verify hashes, encrypt end-to-end, lock down channels, and roll back safely — with OtaKit examples.',
    category: 'Guides',
    publishedAt: '2026-07-08',
    readingTime: '10 min read',
    keywords: [
      'secure OTA updates',
      'Capacitor OTA security',
      'signed update bundles',
      'end-to-end encrypted updates',
      'OTA update integrity',
      'live update security',
    ],
    order: 12,
    relatedDocs: [
      { href: '/docs/security', label: 'Security' },
      { href: '/docs/plugin', label: 'Plugin API' },
      { href: '/docs/channels', label: 'Channels & runtime version' },
    ],
  },
  {
    slug: 'staged-rollouts-for-capacitor-live-updates',
    title: 'Staged rollouts for Capacitor live updates',
    seoTitle: 'Staged & Phased Rollouts for Capacitor Live Updates (2026)',
    description:
      'Ship OTA updates to a slice of users first, watch the health signals, then promote to everyone — or roll back. How to run staged rollouts safely with channels, runtime versions, and OtaKit.',
    category: 'Guides',
    publishedAt: '2026-07-08',
    readingTime: '9 min read',
    keywords: [
      'staged rollout',
      'phased rollout mobile app',
      'canary release Capacitor',
      'gradual OTA rollout',
      'progressive delivery mobile',
      'live update channels',
    ],
    order: 13,
    relatedDocs: [
      { href: '/docs/channels', label: 'Channels & runtime version' },
      { href: '/docs/update-strategies', label: 'Update strategies' },
      { href: '/docs/cli', label: 'CLI reference' },
    ],
  },
  {
    slug: 'app-store-compliant-ota-updates',
    title: 'The ultimate guide to App Store-compliant OTA updates',
    seoTitle: 'App Store-Compliant OTA Updates: The Complete Guide (2026)',
    description:
      'Apple and Google allow over-the-air updates — within limits. Exactly where the compliance line sits, what you can and cannot ship OTA, and how to stay on the right side of guideline 2.5.2 with Capacitor.',
    category: 'Compliance',
    publishedAt: '2026-07-08',
    readingTime: '11 min read',
    keywords: [
      'App Store compliant OTA',
      'OTA updates Apple compliance',
      'guideline 2.5.2',
      'Google Play OTA rules',
      'Capacitor app store approval',
      'live updates policy',
    ],
    order: 14,
    relatedDocs: [
      { href: '/docs/update-strategies', label: 'Update strategies' },
      { href: '/docs/security', label: 'Security' },
      { href: '/docs/setup', label: 'Setup' },
    ],
  },
  {
    slug: 'automate-capacitor-ota-releases-github-actions',
    title: 'Automate Capacitor OTA releases with GitHub Actions',
    seoTitle: 'Automate Capacitor OTA Releases with GitHub Actions (2026)',
    description:
      'Turn every merge to main into a live update: a copy-paste GitHub Actions workflow that builds your web app, uploads the bundle, and releases it to a channel with the OtaKit CLI — no manual steps.',
    category: 'Guides',
    publishedAt: '2026-07-08',
    readingTime: '9 min read',
    keywords: [
      'GitHub Actions Capacitor',
      'CI CD Capacitor OTA',
      'automate live updates',
      'Capacitor release automation',
      'OtaKit CI',
      'continuous delivery mobile app',
    ],
    order: 15,
    relatedDocs: [
      { href: '/docs/ci', label: 'CI automation' },
      { href: '/docs/cli', label: 'CLI reference' },
      { href: '/docs/channels', label: 'Channels & runtime version' },
    ],
  },
  {
    slug: 'react-native-vs-capacitor',
    title: 'React Native vs Capacitor in 2026: which should you pick?',
    seoTitle: 'React Native vs Capacitor (2026): Honest Comparison',
    description:
      'React Native rewrites your UI in native components; Capacitor wraps your existing web app. An honest comparison of performance, ecosystem, team velocity, and over-the-air updates — and when each one wins.',
    category: 'Comparison',
    publishedAt: '2026-07-08',
    readingTime: '11 min read',
    keywords: [
      'React Native vs Capacitor',
      'Capacitor vs React Native',
      'hybrid vs native mobile',
      'Capacitor performance',
      'web to mobile app',
      'React Native alternative',
    ],
    order: 16,
    relatedDocs: [
      { href: '/docs/setup', label: 'Setup' },
      { href: '/docs/react', label: 'React guide' },
      { href: '/docs/update-strategies', label: 'Update strategies' },
    ],
  },
  {
    slug: 'codepush-and-expo-updates-alternatives',
    title: 'CodePush is gone: OTA update alternatives for Capacitor and beyond',
    seoTitle: 'CodePush & Expo Updates Alternatives for Capacitor (2026)',
    description:
      "Microsoft retired CodePush, and Expo's EAS Update only serves React Native. If you're on Capacitor and need over-the-air updates, here are the real alternatives — and how OtaKit compares.",
    category: 'Comparison',
    publishedAt: '2026-07-08',
    readingTime: '9 min read',
    keywords: [
      'CodePush alternative',
      'CodePush shutdown',
      'Expo Updates alternative',
      'EAS Update Capacitor',
      'Capacitor OTA updates',
      'live update service',
    ],
    order: 17,
    relatedDocs: [
      { href: '/docs/setup', label: 'Setup' },
      { href: '/docs/cli', label: 'CLI reference' },
      { href: '/docs/security', label: 'Security' },
    ],
  },
  {
    slug: 'common-capacitor-ota-mistakes',
    title: '7 common Capacitor OTA update mistakes (and how to avoid them)',
    seoTitle: '7 Common Capacitor OTA Update Mistakes to Avoid (2026)',
    description:
      'The failure modes that bite teams shipping live updates: skipping notifyAppReady, breaking native compatibility, no rollback, shipping to everyone at once, ignoring bundle size. What goes wrong and the fix.',
    category: 'Guides',
    publishedAt: '2026-07-08',
    readingTime: '9 min read',
    keywords: [
      'Capacitor OTA mistakes',
      'live update best practices',
      'OTA update errors',
      'notifyAppReady',
      'update rollback',
      'Capacitor update troubleshooting',
    ],
    order: 18,
    relatedDocs: [
      { href: '/docs/update-strategies', label: 'Update strategies' },
      { href: '/docs/plugin', label: 'Plugin API' },
      { href: '/docs/channels', label: 'Channels & runtime version' },
    ],
  },
  {
    slug: 'angular-to-ios-android-with-capacitor',
    title: 'Turn your Angular app into iOS and Android apps with Capacitor',
    seoTitle: 'Angular to iOS & Android with Capacitor (+ Live Updates) 2026',
    description:
      'Convert an existing Angular app into native iOS and Android apps with Capacitor — no rewrite — then push web-layer changes over the air with OtaKit live updates.',
    category: 'Tutorial',
    publishedAt: '2026-07-08',
    readingTime: '10 min read',
    keywords: [
      'Angular mobile app',
      'Angular Capacitor',
      'Angular to native app',
      'Capacitor Angular tutorial',
      'Angular iOS Android',
      'Angular live updates',
    ],
    order: 19,
    relatedDocs: [
      { href: '/docs/setup', label: 'Setup' },
      { href: '/docs/cli', label: 'CLI reference' },
      { href: '/docs/update-strategies', label: 'Update strategies' },
    ],
  },
  {
    slug: 'nuxt-to-ios-android-with-capacitor',
    title: 'Convert your Nuxt app to iOS and Android with Capacitor',
    seoTitle: 'Nuxt to iOS & Android with Capacitor (+ Live Updates) 2026',
    description:
      'Turn a Nuxt 3/4 app into native iOS and Android apps with Capacitor using static generation, add device plugins, and ship instant updates over the air with OtaKit.',
    category: 'Tutorial',
    publishedAt: '2026-07-08',
    readingTime: '10 min read',
    keywords: [
      'Nuxt mobile app',
      'Nuxt Capacitor',
      'Nuxt to native app',
      'Capacitor Nuxt tutorial',
      'Nuxt iOS Android',
      'Nuxt live updates',
    ],
    order: 20,
    relatedDocs: [
      { href: '/docs/setup', label: 'Setup' },
      { href: '/docs/cli', label: 'CLI reference' },
      { href: '/docs/update-strategies', label: 'Update strategies' },
    ],
  },
  {
    slug: 'sveltekit-to-ios-android-with-capacitor',
    title: 'Build iOS and Android apps from your SvelteKit app with Capacitor',
    seoTitle: 'SvelteKit to iOS & Android with Capacitor (+ Live Updates) 2026',
    description:
      'Wrap a SvelteKit app as native iOS and Android with Capacitor using the static adapter, then wire up OtaKit so you can ship JS and CSS changes over the air in minutes.',
    category: 'Tutorial',
    publishedAt: '2026-07-08',
    readingTime: '10 min read',
    keywords: [
      'SvelteKit mobile app',
      'SvelteKit Capacitor',
      'Svelte to native app',
      'Capacitor SvelteKit tutorial',
      'SvelteKit iOS Android',
      'SvelteKit live updates',
    ],
    order: 21,
    relatedDocs: [
      { href: '/docs/setup', label: 'Setup' },
      { href: '/docs/cli', label: 'CLI reference' },
      { href: '/docs/update-strategies', label: 'Update strategies' },
    ],
  },
  {
    slug: 'quasar-to-ios-android-with-capacitor',
    title: 'Ship iOS and Android apps from Quasar with Capacitor live updates',
    seoTitle: 'Quasar to iOS & Android with Capacitor + Live Updates (2026)',
    description:
      'Quasar has a Capacitor mode built in. Here is how to build native iOS and Android apps from your Quasar project and add over-the-air updates with OtaKit.',
    category: 'Tutorial',
    publishedAt: '2026-07-08',
    readingTime: '9 min read',
    keywords: [
      'Quasar mobile app',
      'Quasar Capacitor',
      'Quasar live updates',
      'Capacitor Quasar tutorial',
      'Quasar iOS Android',
      'Vue Quasar native app',
    ],
    order: 22,
    relatedDocs: [
      { href: '/docs/setup', label: 'Setup' },
      { href: '/docs/cli', label: 'CLI reference' },
      { href: '/docs/update-strategies', label: 'Update strategies' },
    ],
  },
  {
    slug: 'vite-app-to-ios-android-with-capacitor',
    title: 'Turn any Vite web app into iOS and Android apps with Capacitor',
    seoTitle: 'Vite App to iOS & Android with Capacitor (+ Live Updates) 2026',
    description:
      'A framework-agnostic guide: take any Vite-built web app to native iOS and Android with Capacitor, then push over-the-air updates with OtaKit. Works with vanilla JS, Solid, Preact, and more.',
    category: 'Tutorial',
    publishedAt: '2026-07-08',
    readingTime: '9 min read',
    keywords: [
      'Vite mobile app',
      'Vite Capacitor',
      'web app to native app',
      'Capacitor Vite tutorial',
      'vanilla JS mobile app',
      'Vite live updates',
    ],
    order: 23,
    relatedDocs: [
      { href: '/docs/setup', label: 'Setup' },
      { href: '/docs/cli', label: 'CLI reference' },
      { href: '/docs/update-strategies', label: 'Update strategies' },
    ],
  },
  {
    slug: 'pwa-to-native-app-with-capacitor',
    title: 'From PWA to native app: ship your PWA to the stores with Capacitor',
    seoTitle: 'PWA to Native App with Capacitor + Live Updates (2026)',
    description:
      'Your PWA already runs everywhere except the App Store. Capacitor wraps it as a native iOS and Android app you can submit, and OtaKit keeps it updated over the air like a PWA.',
    category: 'Tutorial',
    publishedAt: '2026-07-08',
    readingTime: '9 min read',
    keywords: [
      'PWA to native app',
      'PWA Capacitor',
      'PWA to App Store',
      'progressive web app iOS Android',
      'PWA native wrapper',
      'PWA live updates',
    ],
    order: 24,
    relatedDocs: [
      { href: '/docs/setup', label: 'Setup' },
      { href: '/docs/update-strategies', label: 'Update strategies' },
      { href: '/docs/cli', label: 'CLI reference' },
    ],
  },
  {
    slug: 'lovable-app-to-ios-android-with-capacitor',
    title: 'Ship your Lovable (AI-built) app to iOS and Android with Capacitor',
    seoTitle: 'Lovable App to iOS & Android with Capacitor + OTA (2026)',
    description:
      'Built an app with Lovable, v0, or Bolt? Export the code, wrap it with Capacitor for the App Store and Google Play, and iterate fast with OtaKit over-the-air updates.',
    category: 'Tutorial',
    publishedAt: '2026-07-08',
    readingTime: '9 min read',
    keywords: [
      'Lovable to native app',
      'Lovable mobile app',
      'AI app to iOS Android',
      'v0 Bolt Capacitor',
      'AI generated app store',
      'vibe coded app native',
    ],
    order: 25,
    relatedDocs: [
      { href: '/docs/setup', label: 'Setup' },
      { href: '/docs/react', label: 'React guide' },
      { href: '/docs/cli', label: 'CLI reference' },
    ],
  },
  {
    slug: 'ionic-live-updates-with-capacitor',
    title: 'Live updates for Ionic apps with Capacitor and OtaKit',
    seoTitle: 'Ionic Live Updates with Capacitor + OtaKit (2026 Guide)',
    description:
      'Ionic apps run on Capacitor, so they can update over the air. How to add live updates to an Ionic Angular, React, or Vue app with OtaKit — the affordable Appflow Live Updates alternative.',
    category: 'Tutorial',
    publishedAt: '2026-07-08',
    readingTime: '9 min read',
    keywords: [
      'Ionic live updates',
      'Ionic OTA updates',
      'Ionic Capacitor updates',
      'Appflow live updates alternative',
      'Ionic app store bypass',
      'Ionic deploy alternative',
    ],
    order: 26,
    relatedDocs: [
      { href: '/docs/setup', label: 'Setup' },
      { href: '/docs/update-strategies', label: 'Update strategies' },
      { href: '/docs/cli', label: 'CLI reference' },
    ],
  },
  {
    slug: 'how-to-test-capacitor-ota-updates',
    title: 'How to test Capacitor OTA updates before you ship them',
    seoTitle: 'How to Test Capacitor OTA Updates (2026 Guide)',
    description:
      'A repeatable way to test live updates on real devices before production: use a staging channel, verify activation and rollback, and catch native compatibility issues early with OtaKit.',
    category: 'Guides',
    publishedAt: '2026-07-08',
    readingTime: '9 min read',
    keywords: [
      'test OTA updates',
      'test Capacitor live updates',
      'staging channel updates',
      'QA mobile app updates',
      'verify OTA rollback',
      'preview live update',
    ],
    order: 27,
    relatedDocs: [
      { href: '/docs/channels', label: 'Channels & runtime version' },
      { href: '/docs/update-strategies', label: 'Update strategies' },
      { href: '/docs/cli', label: 'CLI reference' },
    ],
  },
  {
    slug: 'forced-and-mandatory-capacitor-updates',
    title: 'Forced and mandatory updates for Capacitor apps',
    seoTitle: 'Forced & Mandatory OTA Updates for Capacitor Apps (2026)',
    description:
      'Sometimes an update cannot wait for the next cold start. How to ship immediate, mandatory OTA updates in Capacitor with OtaKit using force-immediate releases and update policies.',
    category: 'Guides',
    publishedAt: '2026-07-08',
    readingTime: '8 min read',
    keywords: [
      'forced app update',
      'mandatory update mobile',
      'immediate OTA update',
      'force immediate update',
      'Capacitor update policy',
      'critical hotfix mobile',
    ],
    order: 28,
    relatedDocs: [
      { href: '/docs/update-strategies', label: 'Update strategies' },
      { href: '/docs/plugin', label: 'Plugin API' },
      { href: '/docs/events', label: 'Events' },
    ],
  },
  {
    slug: 'semantic-versioning-for-ota-bundles',
    title: 'Semantic versioning for OTA bundles and native runtimes',
    seoTitle: 'Semantic Versioning for Capacitor OTA Bundles (2026)',
    description:
      'How to version OTA bundles and keep them compatible with the native shells in the wild. A practical semver strategy for Capacitor live updates using runtime versions and channels.',
    category: 'Guides',
    publishedAt: '2026-07-08',
    readingTime: '8 min read',
    keywords: [
      'semantic versioning mobile app',
      'OTA bundle version',
      'runtime version Capacitor',
      'app version management',
      'native compatibility updates',
      'versioning live updates',
    ],
    order: 29,
    relatedDocs: [
      { href: '/docs/channels', label: 'Channels & runtime version' },
      { href: '/docs/plugin', label: 'Plugin API' },
      { href: '/docs/update-strategies', label: 'Update strategies' },
    ],
  },
  {
    slug: 'capacitor-ota-rollback-strategies',
    title: 'Rollback strategies for Capacitor OTA updates',
    seoTitle: 'Capacitor OTA Rollback Strategies That Actually Work (2026)',
    description:
      'Automatic rollback, manual rollback, and channel roll-forward: the three ways to recover from a bad live update in Capacitor, when to use each, and how OtaKit makes a broken release a non-event.',
    category: 'Guides',
    publishedAt: '2026-07-08',
    readingTime: '9 min read',
    keywords: [
      'OTA rollback',
      'app update rollback',
      'automatic rollback mobile',
      'roll back live update',
      'Capacitor update recovery',
      'notifyAppReady rollback',
    ],
    order: 30,
    relatedDocs: [
      { href: '/docs/update-strategies', label: 'Update strategies' },
      { href: '/docs/plugin', label: 'Plugin API' },
      { href: '/docs/channels', label: 'Channels & runtime version' },
    ],
  },
  {
    slug: 'background-vs-foreground-app-updates',
    title: 'Background vs foreground app updates: which UX should you pick?',
    seoTitle: 'Background vs Foreground OTA Update UX for Capacitor (2026)',
    description:
      'Silent background updates on next launch, or a restart-to-update prompt? The tradeoffs of each OTA update UX and how to configure both with OtaKit launch and resume policies.',
    category: 'Guides',
    publishedAt: '2026-07-08',
    readingTime: '8 min read',
    keywords: [
      'background app updates',
      'silent OTA update',
      'restart to update prompt',
      'update UX mobile app',
      'Capacitor launch policy',
      'foreground update',
    ],
    order: 31,
    relatedDocs: [
      { href: '/docs/update-strategies', label: 'Update strategies' },
      { href: '/docs/events', label: 'Events' },
      { href: '/docs/plugin', label: 'Plugin API' },
    ],
  },
  {
    slug: 'delta-updates-explained-capacitor',
    title: 'Delta updates explained: download only what changed',
    seoTitle: 'Delta Updates for Capacitor Apps, Explained (2026)',
    description:
      'For asset-heavy apps, full-bundle updates waste bandwidth on files that never changed. How delta updates work, when they matter, and how to enable them in OtaKit with one flag.',
    category: 'Guides',
    publishedAt: '2026-07-08',
    readingTime: '8 min read',
    keywords: [
      'delta updates',
      'differential updates mobile',
      'partial app update',
      'reduce update size',
      'Capacitor delta update',
      'incremental OTA',
    ],
    order: 32,
    relatedDocs: [
      { href: '/docs/update-strategies', label: 'Update strategies' },
      { href: '/docs/cli', label: 'CLI reference' },
      { href: '/docs/plugin', label: 'Plugin API' },
    ],
  },
  {
    slug: 'github-actions-ios-build-signing',
    title: 'Build and sign a Capacitor iOS app in GitHub Actions',
    seoTitle: 'GitHub Actions iOS Build with Signing for Capacitor (2026)',
    description:
      'A complete GitHub Actions workflow to build, sign, and upload a Capacitor iOS app — certificates, provisioning profiles, and the secrets setup — plus shipping the web layer with OtaKit.',
    category: 'Guides',
    publishedAt: '2026-07-08',
    readingTime: '11 min read',
    keywords: [
      'GitHub Actions iOS build',
      'iOS build certificate CI',
      'Capacitor iOS GitHub Actions',
      'provisioning profile CI',
      'sign iOS app CI',
      'fastlane match GitHub Actions',
    ],
    order: 33,
    relatedDocs: [
      { href: '/docs/ci', label: 'CI automation' },
      { href: '/docs/cli', label: 'CLI reference' },
      { href: '/docs/setup', label: 'Setup' },
    ],
  },
  {
    slug: 'github-actions-android-build-capacitor',
    title: 'Build and release a Capacitor Android app with GitHub Actions',
    seoTitle: 'GitHub Actions Android Build for Capacitor Apps (2026)',
    description:
      'Automate your Capacitor Android builds: a GitHub Actions workflow that assembles a signed AAB, handles the keystore securely, and ships web-layer updates with OtaKit.',
    category: 'Guides',
    publishedAt: '2026-07-08',
    readingTime: '10 min read',
    keywords: [
      'GitHub Actions Android build',
      'Capacitor Android CI',
      'sign Android AAB CI',
      'keystore GitHub Actions',
      'Android build automation',
      'Capacitor GitHub Actions',
    ],
    order: 34,
    relatedDocs: [
      { href: '/docs/ci', label: 'CI automation' },
      { href: '/docs/cli', label: 'CLI reference' },
      { href: '/docs/setup', label: 'Setup' },
    ],
  },
  {
    slug: 'gitlab-ci-capacitor-live-updates',
    title: 'Automate Capacitor live updates with GitLab CI/CD',
    seoTitle: 'GitLab CI/CD for Capacitor Live Updates (2026)',
    description:
      'A copy-paste .gitlab-ci.yml that builds your web app and releases an OTA bundle with the OtaKit CLI on every pipeline — the GitLab equivalent of the GitHub Actions flow.',
    category: 'Guides',
    publishedAt: '2026-07-08',
    readingTime: '8 min read',
    keywords: [
      'GitLab CI Capacitor',
      'GitLab CI/CD mobile app',
      'automate live updates GitLab',
      'gitlab-ci.yml Capacitor',
      'OtaKit GitLab',
      'CI CD OTA GitLab',
    ],
    order: 35,
    relatedDocs: [
      { href: '/docs/ci', label: 'CI automation' },
      { href: '/docs/cli', label: 'CLI reference' },
      { href: '/docs/channels', label: 'Channels & runtime version' },
    ],
  },
  {
    slug: 'fastlane-capacitor-ota-releases',
    title: 'Fastlane + OtaKit: automate store builds and OTA releases together',
    seoTitle: 'Fastlane + Capacitor OTA Releases with OtaKit (2026)',
    description:
      'Use Fastlane for the native store builds and OtaKit for the web-layer updates in between. How to combine both in one release lane so store submissions and live updates share a pipeline.',
    category: 'Guides',
    publishedAt: '2026-07-08',
    readingTime: '9 min read',
    keywords: [
      'Fastlane Capacitor',
      'Fastlane OTA updates',
      'Fastlane lane mobile app',
      'automate store submission',
      'Fastlane live updates',
      'Capacitor release lane',
    ],
    order: 36,
    relatedDocs: [
      { href: '/docs/ci', label: 'CI automation' },
      { href: '/docs/cli', label: 'CLI reference' },
      { href: '/docs/update-strategies', label: 'Update strategies' },
    ],
  },
  {
    slug: 'automate-channel-promotion-ota',
    title: 'Automate channel promotion for safe OTA releases',
    seoTitle: 'Automate OTA Channel Promotion (Beta to Production) 2026',
    description:
      'Promote the exact bundle you validated from beta to production automatically — on a schedule, a tag, or a manual approval gate. Channel-promotion patterns for Capacitor live updates with OtaKit.',
    category: 'Guides',
    publishedAt: '2026-07-08',
    readingTime: '8 min read',
    keywords: [
      'channel promotion',
      'promote beta to production',
      'OTA release pipeline',
      'approval gate mobile release',
      'Capacitor channel automation',
      'progressive delivery CI',
    ],
    order: 37,
    relatedDocs: [
      { href: '/docs/channels', label: 'Channels & runtime version' },
      { href: '/docs/ci', label: 'CI automation' },
      { href: '/docs/cli', label: 'CLI reference' },
    ],
  },
  {
    slug: 'apple-guideline-2-5-2-explained',
    title: 'Apple guideline 2.5.2 explained for OTA updates',
    seoTitle: 'Apple Guideline 2.5.2 Explained for OTA Updates (2026)',
    description:
      'The exact wording of App Store Review Guideline 2.5.2, the WebKit/JavaScriptCore exception it grants, and what it means in practice for Capacitor apps shipping over-the-air updates.',
    category: 'Compliance',
    publishedAt: '2026-07-08',
    readingTime: '9 min read',
    keywords: [
      'guideline 2.5.2',
      'Apple 2.5.2 OTA',
      'App Store executable code rule',
      'Apple 3.3.1 interpreted code',
      'App Store OTA compliance',
      'WebKit JavaScriptCore exception',
    ],
    order: 38,
    relatedDocs: [
      { href: '/docs/update-strategies', label: 'Update strategies' },
      { href: '/docs/security', label: 'Security' },
      { href: '/docs/setup', label: 'Setup' },
    ],
  },
  {
    slug: 'google-play-ota-compliance-checklist',
    title: 'Google Play OTA compliance: a developer checklist',
    seoTitle: 'Google Play OTA Update Compliance Checklist (2026)',
    description:
      "What Google Play's Device and Network Abuse policy actually restricts, why interpreted web-layer updates stay within policy, and a checklist to keep your Capacitor OTA setup compliant.",
    category: 'Compliance',
    publishedAt: '2026-07-08',
    readingTime: '8 min read',
    keywords: [
      'Google Play OTA policy',
      'Google Play compliance checklist',
      'device and network abuse policy',
      'Android OTA updates rules',
      'Google Play executable code',
      'Capacitor Google Play compliance',
    ],
    order: 39,
    relatedDocs: [
      { href: '/docs/update-strategies', label: 'Update strategies' },
      { href: '/docs/security', label: 'Security' },
      { href: '/docs/setup', label: 'Setup' },
    ],
  },
  {
    slug: 'ios-privacy-manifest-for-capacitor',
    title: 'The iOS privacy manifest for Capacitor apps, explained',
    seoTitle: 'iOS Privacy Manifest for Capacitor Apps (2026 Guide)',
    description:
      "Apple's privacy manifest and required-reason APIs are now mandatory. What a Capacitor app needs in its PrivacyInfo.xcprivacy, how plugins factor in, and common submission errors to avoid.",
    category: 'Compliance',
    publishedAt: '2026-07-08',
    readingTime: '9 min read',
    keywords: [
      'iOS privacy manifest',
      'PrivacyInfo.xcprivacy',
      'required reason API',
      'Capacitor privacy manifest',
      'Apple privacy requirements',
      'app privacy report',
    ],
    order: 40,
    relatedDocs: [
      { href: '/docs/setup', label: 'Setup' },
      { href: '/docs/plugin', label: 'Plugin API' },
      { href: '/docs/security', label: 'Security' },
    ],
  },
  {
    slug: 'first-app-store-review-guide',
    title: 'Passing your first App Store and Google Play review',
    seoTitle: 'Your First App Store & Google Play Review Guide (2026)',
    description:
      'The most common reasons first submissions get rejected, a pre-submission checklist for Capacitor apps, and how OTA updates let you fix post-launch issues without waiting on another review.',
    category: 'Compliance',
    publishedAt: '2026-07-08',
    readingTime: '10 min read',
    keywords: [
      'first app store review',
      'app store rejection reasons',
      'app review checklist',
      'submit app to App Store',
      'Google Play review guide',
      'Capacitor app submission',
    ],
    order: 41,
    relatedDocs: [
      { href: '/docs/setup', label: 'Setup' },
      { href: '/docs/update-strategies', label: 'Update strategies' },
      { href: '/docs/security', label: 'Security' },
    ],
  },
  {
    slug: 'capacitor-vs-appflow',
    title: 'Capacitor + OtaKit vs Ionic Appflow for live updates',
    seoTitle: 'Capacitor OTA vs Ionic Appflow: Live Updates Compared (2026)',
    description:
      'Ionic Appflow bundles live updates into a broader paid platform. A focused comparison of Appflow live updates vs OtaKit on price, delivery, rollback, encryption, and lock-in.',
    category: 'Comparison',
    publishedAt: '2026-07-08',
    readingTime: '9 min read',
    keywords: [
      'Capacitor vs Appflow',
      'Appflow live updates',
      'Ionic Appflow comparison',
      'Appflow pricing',
      'Appflow vs OtaKit',
      'Appflow deploy alternative',
    ],
    order: 42,
    relatedDocs: [
      { href: '/docs/setup', label: 'Setup' },
      { href: '/docs/cli', label: 'CLI reference' },
      { href: '/docs/update-strategies', label: 'Update strategies' },
    ],
  },
  {
    slug: 'ionic-appflow-alternative',
    title: 'The best Ionic Appflow alternative for live updates',
    seoTitle: 'Ionic Appflow Alternative: Cheaper Live Updates (2026)',
    description:
      'Looking for an Appflow alternative for live updates? OtaKit ships the same OTA capability with no per-seat platform pricing, CDN-direct delivery, delta updates, and an open-source stack.',
    category: 'Comparison',
    publishedAt: '2026-07-08',
    readingTime: '7 min read',
    keywords: [
      'Appflow alternative',
      'Ionic Appflow alternative',
      'Appflow live updates alternative',
      'Ionic deploy alternative',
      'cheaper than Appflow',
      'Capacitor OTA service',
    ],
    order: 43,
    relatedDocs: [
      { href: '/docs/setup', label: 'Setup' },
      { href: '/docs/cli', label: 'CLI reference' },
      { href: '/docs/security', label: 'Security' },
    ],
  },
  {
    slug: 'best-ota-tools-for-capacitor-2026',
    title: 'The best OTA update tools for Capacitor in 2026',
    seoTitle: 'Best OTA / Live Update Tools for Capacitor (2026)',
    description:
      'A buyer-focused roundup of live update tools for Capacitor apps — OtaKit, Capgo, Capawesome, and Appflow — compared on pricing model, delivery, security, and self-hosting.',
    category: 'Comparison',
    publishedAt: '2026-07-08',
    readingTime: '10 min read',
    keywords: [
      'best OTA tools Capacitor',
      'live update tools 2026',
      'Capacitor update service comparison',
      'OTA provider comparison',
      'mobile app update tools',
      'Capacitor live update options',
    ],
    order: 44,
    relatedDocs: [
      { href: '/docs/channels', label: 'Channels & runtime version' },
      { href: '/docs/cli', label: 'CLI reference' },
      { href: '/docs/security', label: 'Security' },
    ],
  },
  {
    slug: 'eas-update-vs-capacitor-ota',
    title: 'EAS Update vs Capacitor OTA: which live-update path fits you?',
    seoTitle: 'EAS Update vs Capacitor OTA Updates Compared (2026)',
    description:
      "Expo's EAS Update serves React Native; Capacitor OTA serves web-layer apps. A comparison of the two live-update models, their ecosystems, and how to choose based on your stack.",
    category: 'Comparison',
    publishedAt: '2026-07-08',
    readingTime: '9 min read',
    keywords: [
      'EAS Update vs Capacitor',
      'Expo Updates alternative',
      'EAS Update comparison',
      'React Native vs Capacitor updates',
      'live update ecosystems',
      'Capacitor OTA vs Expo',
    ],
    order: 45,
    relatedDocs: [
      { href: '/docs/setup', label: 'Setup' },
      { href: '/docs/update-strategies', label: 'Update strategies' },
      { href: '/docs/cli', label: 'CLI reference' },
    ],
  },
  {
    slug: 'capgo-vs-capawesome',
    title: 'Capgo vs Capawesome vs OtaKit: an honest 2026 comparison',
    seoTitle: 'Capgo vs Capawesome vs OtaKit: Honest Comparison (2026)',
    description:
      'The two best-known Capacitor live-update tools compared head to head on pricing, MAU metering, features, and open-source stance — with OtaKit as the no-metering third option.',
    category: 'Comparison',
    publishedAt: '2026-07-08',
    readingTime: '9 min read',
    keywords: [
      'Capgo vs Capawesome',
      'Capawesome vs Capgo',
      'Capacitor live update comparison',
      'Capgo pricing',
      'Capawesome pricing',
      'OtaKit comparison',
    ],
    order: 46,
    relatedDocs: [
      { href: '/docs/channels', label: 'Channels & runtime version' },
      { href: '/docs/cli', label: 'CLI reference' },
      { href: '/docs/security', label: 'Security' },
    ],
  },
  {
    slug: 'reduce-capacitor-app-bundle-size',
    title: 'How to reduce your Capacitor app bundle size',
    seoTitle: 'How to Reduce Capacitor App Bundle Size (2026)',
    description:
      'Smaller bundles mean faster startups and faster OTA updates. Practical ways to shrink a Capacitor web bundle — code splitting, asset optimization, tree shaking — and why delta updates finish the job.',
    category: 'Guides',
    publishedAt: '2026-07-08',
    readingTime: '9 min read',
    keywords: [
      'reduce app bundle size',
      'Capacitor bundle size',
      'optimize web bundle',
      'code splitting mobile app',
      'smaller OTA updates',
      'app performance bundle',
    ],
    order: 47,
    relatedDocs: [
      { href: '/docs/update-strategies', label: 'Update strategies' },
      { href: '/docs/cli', label: 'CLI reference' },
      { href: '/docs/plugin', label: 'Plugin API' },
    ],
  },
  {
    slug: 'feature-flags-in-capacitor-apps',
    title: 'Feature flags in Capacitor apps with OTA updates',
    seoTitle: 'Feature Flags in Capacitor Apps with OTA Updates (2026)',
    description:
      'Combine feature flags with over-the-air updates to ship dark, flip features on remotely, and run controlled rollouts — without a store release. Patterns for Capacitor apps using OtaKit channels.',
    category: 'Guides',
    publishedAt: '2026-07-08',
    readingTime: '8 min read',
    keywords: [
      'feature flags mobile app',
      'feature flags Capacitor',
      'remote config mobile',
      'ship dark feature flag',
      'controlled rollout flags',
      'OTA feature toggle',
    ],
    order: 48,
    relatedDocs: [
      { href: '/docs/channels', label: 'Channels & runtime version' },
      { href: '/docs/update-strategies', label: 'Update strategies' },
      { href: '/docs/events', label: 'Events' },
    ],
  },
];

export function getBlogPosts() {
  return [...BLOG_POSTS].sort((a, b) => a.order - b.order);
}

export function getBlogPost(slug: string) {
  return BLOG_POSTS.find((post) => post.slug === slug);
}

/** Build full Next.js metadata (canonical, OG article, Twitter) for a post. */
export function blogPostMetadata(slug: string): Metadata {
  const post = getBlogPost(slug);
  if (!post) return {};

  const url = `${site.url}/blog/${post.slug}`;
  const title = post.seoTitle ?? post.title;

  return {
    title,
    description: post.description,
    keywords: post.keywords,
    alternates: { canonical: url },
    openGraph: {
      title,
      description: post.description,
      url,
      siteName: site.name,
      type: 'article',
      publishedTime: post.publishedAt,
      modifiedTime: post.updatedAt ?? post.publishedAt,
    },
    twitter: {
      card: 'summary_large_image',
      title,
      description: post.description,
    },
  };
}
