import type { Metadata } from 'next';

import { site } from '@/lib/site';

export type BlogPostMeta = {
  slug: string;
  title: string;
  /** Title used in <title> / OG. Defaults to `title` when omitted. */
  seoTitle?: string;
  description: string;
  category: 'Guides' | 'Comparison' | 'Compliance' | 'Migration' | 'Tutorial';
  publishedAt: string;
  updatedAt?: string;
  readingTime: string;
  keywords: string[];
  order: number;
  featured?: boolean;
  relatedDocs: Array<{
    href: string;
    label: string;
  }>;
};

export const BLOG_POSTS: BlogPostMeta[] = [
  {
    slug: 'ship-capacitor-updates-with-ai-agents',
    title: 'Ship Capacitor updates with AI agents',
    seoTitle: 'Ship Capacitor OTA Updates With AI Agents',
    description:
      'Ask Claude Code or Codex to ship an OTA update. It checks compatibility, uploads, and stops for your approval before anything reaches a device.',
    category: 'Guides',
    publishedAt: '2026-08-30',
    readingTime: '4 min read',
    keywords: [
      'Capacitor MCP server',
      'Capacitor Agent Skill',
      'AI agent OTA updates',
      'Codex Capacitor',
      'Claude Code live updates',
      'OtaKit MCP',
    ],
    order: 0,
    featured: true,
    relatedDocs: [
      { href: '/docs/agents', label: 'MCP & Agent Skills' },
      { href: '/docs/cli', label: 'CLI reference' },
      { href: '/docs/channels', label: 'Channels & runtime version' },
    ],
  },
  {
    slug: 'google-play-api-36-deadline',
    title: 'Google Play now requires API 36',
    seoTitle: 'Google Play API 36 Deadline: What Capacitor Apps Must Do',
    description:
      'Since 31 August 2026, Google Play rejects new apps and updates that target below Android 16 (API 36). What changed, what it means for a Capacitor app, and the extension to 1 November.',
    category: 'Compliance',
    publishedAt: '2026-09-02',
    readingTime: '6 min read',
    keywords: [
      'Google Play API 36',
      'target API level 36',
      'Android 16 target SDK',
      'Play Store deadline 2026',
      'Capacitor targetSdkVersion',
      'Google Play compliance',
    ],
    order: 1,
    relatedDocs: [
      { href: '/docs/setup', label: 'Setup' },
      { href: '/docs/channels', label: 'Channels & runtime version' },
      { href: '/docs/ci', label: 'CI automation' },
    ],
  },
  {
    slug: 'ios-27-uiscene-capacitor',
    title: 'iOS 27 makes UIScene mandatory',
    seoTitle: 'iOS 27 UIScene Migration for Capacitor Apps',
    description:
      'Apps built with the iOS 27 SDK must adopt the scene-based lifecycle or they do not launch at all. What Capacitor 8.5 changed, the two-command migration, and where it goes wrong.',
    category: 'Guides',
    publishedAt: '2026-09-02',
    readingTime: '7 min read',
    keywords: [
      'iOS 27 UIScene',
      'UIScene life cycle required',
      'Capacitor 8.5 migration',
      'Xcode 27 Capacitor',
      'UIApplicationSceneManifest',
      'cap migrate',
    ],
    order: 2,
    relatedDocs: [
      { href: '/docs/setup', label: 'Setup' },
      { href: '/docs/update-strategies', label: 'Update strategies' },
      { href: '/docs/ci', label: 'CI automation' },
    ],
  },
  {
    slug: 'capacitor-9-what-changes',
    title: 'Capacitor 9: what changes, and what to do first',
    seoTitle: 'Capacitor 9: What Changes and How to Prepare',
    description:
      'Capacitor 9 is forecast for the end of November 2026: Cordova becomes optional, the iOS runtime is Swift, XCFramework distribution ends. Plus the CocoaPods deadline hiding inside it.',
    category: 'Guides',
    publishedAt: '2026-09-02',
    readingTime: '8 min read',
    keywords: [
      'Capacitor 9',
      'Capacitor 9 release date',
      'Capacitor 9 breaking changes',
      'CocoaPods read-only',
      'Capacitor SPM migration',
      'Capacitor upgrade guide',
    ],
    order: 3,
    relatedDocs: [
      { href: '/docs/setup', label: 'Setup' },
      { href: '/docs/channels', label: 'Channels & runtime version' },
      { href: '/docs/plugin', label: 'Plugin reference' },
    ],
  },
  {
    slug: 'how-ota-works-for-capacitor-apps',
    title: 'How OTA updates work in Capacitor apps',
    seoTitle: 'How OTA Updates Work in Capacitor Apps',
    description:
      'What actually happens when a Capacitor app updates over the air: bundles, channels, signed manifests, delta downloads, safe activation, and automatic rollback.',
    category: 'Guides',
    publishedAt: '2026-07-02',
    readingTime: '9 min read',
    keywords: [
      'Capacitor OTA updates',
      'over-the-air updates',
      'Capacitor live updates',
      'how OTA works',
      'app update rollback',
      'update channels',
    ],
    order: 6,
    relatedDocs: [
      { href: '/docs/setup', label: 'Setup' },
      { href: '/docs/update-strategies', label: 'Update strategies' },
      { href: '/docs/security', label: 'Security' },
    ],
  },
  {
    slug: 'ota-policies-for-app-store-and-google-play',
    title: 'Are OTA updates allowed? App Store and Google Play rules, explained',
    seoTitle: 'Are OTA Updates Allowed? App Store & Google Play Rules Explained',
    description:
      'What Apple and Google actually say about over-the-air updates, quoted from the primary sources — and the practical line between compliant web-layer updates and rejection territory.',
    category: 'Compliance',
    publishedAt: '2026-07-02',
    readingTime: '9 min read',
    keywords: [
      'are OTA updates allowed',
      'App Store OTA policy',
      'Google Play OTA policy',
      'guideline 2.5.2',
      'Apple 3.3.1B interpreted code',
      'Capacitor app store compliance',
      'CodePush legal',
    ],
    order: 7,
    relatedDocs: [
      { href: '/docs/setup', label: 'Setup' },
      { href: '/docs/plugin', label: 'Plugin API' },
      { href: '/docs/security', label: 'Security' },
    ],
  },
  {
    slug: 'best-live-update-frameworks-for-capacitor-apps',
    title: 'The best live update tools for Capacitor apps in 2026',
    seoTitle: 'Best Live Update Tools for Capacitor Apps in 2026 (Compared)',
    description:
      'OtaKit vs Capgo vs Capawesome, compared honestly: pricing, delivery architecture, security, agent workflows, and which one fits your Capacitor release process.',
    category: 'Comparison',
    publishedAt: '2026-07-02',
    updatedAt: '2026-08-30',
    readingTime: '10 min read',
    keywords: [
      'best Capacitor live update',
      'Capacitor OTA comparison',
      'OtaKit vs Capgo',
      'OtaKit vs Capawesome',
      'Capgo vs Capawesome',
      'CodePush alternative Capacitor',
      'Capacitor MCP',
    ],
    order: 8,
    relatedDocs: [
      { href: '/docs/channels', label: 'Channels & runtime version' },
      { href: '/docs/cli', label: 'CLI reference' },
      { href: '/docs/agents', label: 'MCP & Agent Skills' },
    ],
  },
  {
    slug: 'the-1-alternative-to-capgo-capawesome',
    title: 'Why OtaKit is the better, cheaper alternative to Capgo and Capawesome',
    seoTitle: 'The Better, Cheaper Alternative to Capgo and Capawesome (2026)',
    description:
      'OtaKit delivers the same live updates for a fraction of the price: no MAU metering, CDN-direct delivery, delta updates, end-to-end encryption, and a fully MIT-licensed stack.',
    category: 'Comparison',
    publishedAt: '2026-07-02',
    readingTime: '7 min read',
    keywords: [
      'Capgo alternative',
      'Capawesome alternative',
      'Capacitor live update pricing',
      'open source OTA updates',
      'self-hosted live updates',
    ],
    order: 9,
    relatedDocs: [
      { href: '/docs/setup', label: 'Setup' },
      { href: '/docs/channels', label: 'Channels & runtime version' },
      { href: '/docs/security', label: 'Security' },
    ],
  },
  {
    slug: 'capgo-alternative',
    title: 'The cheaper, better Capgo alternative for Capacitor live updates',
    seoTitle: 'Capgo Alternative: Cheaper, Better Live Updates for Capacitor (2026)',
    description:
      'Looking for a Capgo alternative? Compare OtaKit pricing, CDN-direct delivery, open-source architecture, release controls, MCP, and Agent Skills.',
    category: 'Comparison',
    publishedAt: '2026-07-02',
    updatedAt: '2026-08-30',
    readingTime: '6 min read',
    keywords: [
      'Capgo alternative',
      'Capgo pricing',
      'Capgo vs OtaKit',
      'Capacitor live updates',
      'capacitor-updater alternative',
      'Capgo migration',
    ],
    order: 10,
    relatedDocs: [
      { href: '/docs/setup', label: 'Setup' },
      { href: '/docs/cli', label: 'CLI reference' },
      { href: '/docs/agents', label: 'MCP & Agent Skills' },
    ],
  },
  {
    slug: 'capawesome-alternative',
    title: 'The cheaper, better Capawesome alternative for live updates',
    seoTitle: 'Capawesome Alternative: Cheaper, Better Live Updates for Capacitor (2026)',
    description:
      'Looking for a Capawesome Live Update alternative? Compare OtaKit pricing, CDN-direct delivery, open-source architecture, release controls, MCP, and Agent Skills.',
    category: 'Comparison',
    publishedAt: '2026-07-02',
    updatedAt: '2026-08-30',
    readingTime: '6 min read',
    keywords: [
      'Capawesome alternative',
      'Capawesome Live Update pricing',
      'Capawesome vs OtaKit',
      'Capacitor live updates',
      'capacitor-live-update alternative',
    ],
    order: 11,
    relatedDocs: [
      { href: '/docs/setup', label: 'Setup' },
      { href: '/docs/update-strategies', label: 'Update strategies' },
      { href: '/docs/agents', label: 'MCP & Agent Skills' },
    ],
  },
  {
    slug: 'vibe-code-an-app-from-your-mobile-with-claude-code-remote-and-otakit',
    title: 'Vibe code your app from your phone with Claude Code and OtaKit',
    seoTitle: 'Vibe Code an App From Your Phone With Claude Code + OTA Updates',
    description:
      'A real mobile-only dev loop: drive Claude Code from your phone, build in the cloud, and ship to your installed Capacitor app through CI or the OtaKit MCP server.',
    category: 'Guides',
    publishedAt: '2026-07-02',
    updatedAt: '2026-08-30',
    readingTime: '7 min read',
    keywords: [
      'Claude Code mobile',
      'vibe coding',
      'code from phone',
      'Capacitor OTA workflow',
      'Claude Code Capacitor',
      'ship app updates from phone',
    ],
    order: 4,
    featured: true,
    relatedDocs: [
      { href: '/docs/react', label: 'React guide' },
      { href: '/docs/guide', label: 'Next.js guide' },
      { href: '/docs/ci', label: 'CI automation' },
      { href: '/docs/agents', label: 'MCP & Agent Skills' },
    ],
  },
  {
    slug: 'migrate-from-capgo-and-capawesome',
    title: 'How to migrate from Capgo or Capawesome to OtaKit',
    seoTitle: 'Migrate From Capgo or Capawesome to OtaKit: Complete Guide',
    description:
      'A production-grade migration guide: exact config and API translations from Capgo and Capawesome to OtaKit, what maps cleanly, and a safe cutover plan for your install base.',
    category: 'Migration',
    publishedAt: '2026-07-02',
    readingTime: '14 min read',
    keywords: [
      'migrate from Capgo',
      'migrate from Capawesome',
      'Capgo migration guide',
      'Capacitor updater migration',
      'switch OTA provider',
    ],
    order: 5,
    featured: true,
    relatedDocs: [
      { href: '/docs/setup', label: 'Setup' },
      { href: '/docs/cli', label: 'CLI reference' },
      { href: '/docs/update-strategies', label: 'Update strategies' },
    ],
  },
  {
    slug: 'nextjs-to-ios-android-with-capacitor',
    title: 'Convert your Next.js app to iOS and Android with Capacitor',
    seoTitle: 'Next.js to iOS & Android with Capacitor (+ Live Updates) 2026',
    description:
      'Turn an existing Next.js app into real iOS and Android apps with Capacitor — static export config, native project setup, plugins, safe areas — then ship JS/CSS changes instantly with OtaKit live updates.',
    category: 'Tutorial',
    publishedAt: '2026-07-08',
    readingTime: '11 min read',
    keywords: [
      'Next.js mobile app',
      'Next.js Capacitor',
      'Next.js iOS Android',
      'convert Next.js to mobile app',
      'Capacitor 8 Next.js',
      'Next.js live updates',
    ],
    order: 12,
    featured: true,
    relatedDocs: [
      { href: '/docs/guide', label: 'Next.js guide' },
      { href: '/docs/setup', label: 'Setup' },
      { href: '/docs/cli', label: 'CLI reference' },
    ],
  },
  {
    slug: 'react-to-ios-android-with-capacitor',
    title: 'Turn your React app into iOS and Android apps with Capacitor',
    seoTitle: 'React to iOS & Android with Capacitor (+ Live Updates) 2026',
    description:
      'A step-by-step guide to wrapping a plain React (Vite) app as native iOS and Android with Capacitor — no React Native rewrite — plus over-the-air updates with OtaKit so you can ship fixes without a store review.',
    category: 'Tutorial',
    publishedAt: '2026-07-08',
    readingTime: '10 min read',
    keywords: [
      'React mobile app',
      'React Capacitor',
      'React to native app',
      'Capacitor React tutorial',
      'React iOS Android',
      'React live updates',
    ],
    order: 13,
    relatedDocs: [
      { href: '/docs/react', label: 'React guide' },
      { href: '/docs/setup', label: 'Setup' },
      { href: '/docs/update-strategies', label: 'Update strategies' },
    ],
  },
  {
    slug: 'vue-to-ios-android-with-capacitor',
    title: 'Build iOS and Android apps from your Vue app with Capacitor',
    seoTitle: 'Vue to iOS & Android with Capacitor (+ Live Updates) 2026',
    description:
      'Convert a Vue 3 (Vite) web app into native iOS and Android apps with Capacitor, add device plugins, and wire up OtaKit live updates to push web-layer changes over the air in minutes.',
    category: 'Tutorial',
    publishedAt: '2026-07-08',
    readingTime: '10 min read',
    keywords: [
      'Vue mobile app',
      'Vue Capacitor',
      'Vue to native app',
      'Capacitor Vue tutorial',
      'Vue iOS Android',
      'Vue live updates',
    ],
    order: 14,
    relatedDocs: [
      { href: '/docs/setup', label: 'Setup' },
      { href: '/docs/cli', label: 'CLI reference' },
      { href: '/docs/update-strategies', label: 'Update strategies' },
    ],
  },
  {
    slug: 'capacitor-ota-update-security',
    title: 'How to secure Capacitor OTA updates',
    seoTitle: 'Capacitor OTA Update Security: A Practical Guide (2026)',
    description:
      'OTA updates ship code to production devices, so the pipeline is a security surface. How to sign bundles, verify hashes, encrypt end-to-end, lock down channels, and roll back safely — with OtaKit examples.',
    category: 'Guides',
    publishedAt: '2026-07-08',
    readingTime: '10 min read',
    keywords: [
      'secure OTA updates',
      'Capacitor OTA security',
      'signed update bundles',
      'end-to-end encrypted updates',
      'OTA update integrity',
      'live update security',
    ],
    order: 15,
    relatedDocs: [
      { href: '/docs/security', label: 'Security' },
      { href: '/docs/plugin', label: 'Plugin API' },
      { href: '/docs/channels', label: 'Channels & runtime version' },
    ],
  },
  {
    slug: 'staged-rollouts-for-capacitor-live-updates',
    title: 'Staged rollouts for Capacitor live updates',
    seoTitle: 'Staged & Phased Rollouts for Capacitor Live Updates (2026)',
    description:
      'Ship OTA updates to a slice of users first, watch the health signals, then promote to everyone — or roll back. How to run staged rollouts safely with channels, runtime versions, and OtaKit.',
    category: 'Guides',
    publishedAt: '2026-07-08',
    readingTime: '9 min read',
    keywords: [
      'staged rollout',
      'phased rollout mobile app',
      'canary release Capacitor',
      'gradual OTA rollout',
      'progressive delivery mobile',
      'live update channels',
    ],
    order: 16,
    relatedDocs: [
      { href: '/docs/channels', label: 'Channels & runtime version' },
      { href: '/docs/update-strategies', label: 'Update strategies' },
      { href: '/docs/cli', label: 'CLI reference' },
    ],
  },
  {
    slug: 'app-store-compliant-ota-updates',
    title: 'The ultimate guide to App Store-compliant OTA updates',
    seoTitle: 'App Store-Compliant OTA Updates: The Complete Guide (2026)',
    description:
      'Apple and Google allow over-the-air updates — within limits. Exactly where the compliance line sits, what you can and cannot ship OTA, and how to stay on the right side of guideline 2.5.2 with Capacitor.',
    category: 'Compliance',
    publishedAt: '2026-07-08',
    readingTime: '11 min read',
    keywords: [
      'App Store compliant OTA',
      'OTA updates Apple compliance',
      'guideline 2.5.2',
      'Google Play OTA rules',
      'Capacitor app store approval',
      'live updates policy',
    ],
    order: 17,
    relatedDocs: [
      { href: '/docs/update-strategies', label: 'Update strategies' },
      { href: '/docs/security', label: 'Security' },
      { href: '/docs/setup', label: 'Setup' },
    ],
  },
  {
    slug: 'automate-capacitor-ota-releases-github-actions',
    title: 'Automate Capacitor OTA releases with GitHub Actions',
    seoTitle: 'Automate Capacitor OTA Releases with GitHub Actions (2026)',
    description:
      'Turn every merge to main into a live update: a copy-paste GitHub Actions workflow that builds your web app, uploads the bundle, and releases it to a channel with the OtaKit CLI — no manual steps.',
    category: 'Guides',
    publishedAt: '2026-07-08',
    readingTime: '9 min read',
    keywords: [
      'GitHub Actions Capacitor',
      'CI CD Capacitor OTA',
      'automate live updates',
      'Capacitor release automation',
      'OtaKit CI',
      'continuous delivery mobile app',
    ],
    order: 18,
    relatedDocs: [
      { href: '/docs/ci', label: 'CI automation' },
      { href: '/docs/cli', label: 'CLI reference' },
      { href: '/docs/channels', label: 'Channels & runtime version' },
    ],
  },
  {
    slug: 'react-native-vs-capacitor',
    title: 'React Native vs Capacitor in 2026: which should you pick?',
    seoTitle: 'React Native vs Capacitor (2026): Honest Comparison',
    description:
      'React Native rewrites your UI in native components; Capacitor wraps your existing web app. An honest comparison of performance, ecosystem, team velocity, and over-the-air updates — and when each one wins.',
    category: 'Comparison',
    publishedAt: '2026-07-08',
    readingTime: '11 min read',
    keywords: [
      'React Native vs Capacitor',
      'Capacitor vs React Native',
      'hybrid vs native mobile',
      'Capacitor performance',
      'web to mobile app',
      'React Native alternative',
    ],
    order: 19,
    relatedDocs: [
      { href: '/docs/setup', label: 'Setup' },
      { href: '/docs/react', label: 'React guide' },
      { href: '/docs/update-strategies', label: 'Update strategies' },
    ],
  },
  {
    slug: 'codepush-and-expo-updates-alternatives',
    title: 'CodePush is gone: OTA update alternatives for Capacitor and beyond',
    seoTitle: 'CodePush & Expo Updates Alternatives for Capacitor (2026)',
    description:
      "Microsoft retired CodePush, and Expo's EAS Update only serves React Native. If you're on Capacitor and need over-the-air updates, here are the real alternatives — and how OtaKit compares.",
    category: 'Comparison',
    publishedAt: '2026-07-08',
    readingTime: '9 min read',
    keywords: [
      'CodePush alternative',
      'CodePush shutdown',
      'Expo Updates alternative',
      'EAS Update Capacitor',
      'Capacitor OTA updates',
      'live update service',
    ],
    order: 20,
    relatedDocs: [
      { href: '/docs/setup', label: 'Setup' },
      { href: '/docs/cli', label: 'CLI reference' },
      { href: '/docs/security', label: 'Security' },
    ],
  },
  {
    slug: 'common-capacitor-ota-mistakes',
    title: '7 common Capacitor OTA update mistakes (and how to avoid them)',
    seoTitle: '7 Common Capacitor OTA Update Mistakes to Avoid (2026)',
    description:
      'The failure modes that bite teams shipping live updates: skipping notifyAppReady, breaking native compatibility, no rollback, shipping to everyone at once, ignoring bundle size. What goes wrong and the fix.',
    category: 'Guides',
    publishedAt: '2026-07-08',
    readingTime: '9 min read',
    keywords: [
      'Capacitor OTA mistakes',
      'live update best practices',
      'OTA update errors',
      'notifyAppReady',
      'update rollback',
      'Capacitor update troubleshooting',
    ],
    order: 21,
    relatedDocs: [
      { href: '/docs/update-strategies', label: 'Update strategies' },
      { href: '/docs/plugin', label: 'Plugin API' },
      { href: '/docs/channels', label: 'Channels & runtime version' },
    ],
  },
  {
    slug: 'angular-to-ios-android-with-capacitor',
    title: 'Turn your Angular app into iOS and Android apps with Capacitor',
    seoTitle: 'Angular to iOS & Android with Capacitor (+ Live Updates) 2026',
    description:
      'Convert an existing Angular app into native iOS and Android apps with Capacitor — no rewrite — then push web-layer changes over the air with OtaKit live updates.',
    category: 'Tutorial',
    publishedAt: '2026-07-08',
    readingTime: '10 min read',
    keywords: [
      'Angular mobile app',
      'Angular Capacitor',
      'Angular to native app',
      'Capacitor Angular tutorial',
      'Angular iOS Android',
      'Angular live updates',
    ],
    order: 22,
    relatedDocs: [
      { href: '/docs/setup', label: 'Setup' },
      { href: '/docs/cli', label: 'CLI reference' },
      { href: '/docs/update-strategies', label: 'Update strategies' },
    ],
  },
  {
    slug: 'nuxt-to-ios-android-with-capacitor',
    title: 'Convert your Nuxt app to iOS and Android with Capacitor',
    seoTitle: 'Nuxt to iOS & Android with Capacitor (+ Live Updates) 2026',
    description:
      'Turn a Nuxt 3/4 app into native iOS and Android apps with Capacitor using static generation, add device plugins, and ship instant updates over the air with OtaKit.',
    category: 'Tutorial',
    publishedAt: '2026-07-08',
    readingTime: '10 min read',
    keywords: [
      'Nuxt mobile app',
      'Nuxt Capacitor',
      'Nuxt to native app',
      'Capacitor Nuxt tutorial',
      'Nuxt iOS Android',
      'Nuxt live updates',
    ],
    order: 23,
    relatedDocs: [
      { href: '/docs/setup', label: 'Setup' },
      { href: '/docs/cli', label: 'CLI reference' },
      { href: '/docs/update-strategies', label: 'Update strategies' },
    ],
  },
  {
    slug: 'sveltekit-to-ios-android-with-capacitor',
    title: 'Build iOS and Android apps from your SvelteKit app with Capacitor',
    seoTitle: 'SvelteKit to iOS & Android with Capacitor (+ Live Updates) 2026',
    description:
      'Wrap a SvelteKit app as native iOS and Android with Capacitor using the static adapter, then wire up OtaKit so you can ship JS and CSS changes over the air in minutes.',
    category: 'Tutorial',
    publishedAt: '2026-07-08',
    readingTime: '10 min read',
    keywords: [
      'SvelteKit mobile app',
      'SvelteKit Capacitor',
      'Svelte to native app',
      'Capacitor SvelteKit tutorial',
      'SvelteKit iOS Android',
      'SvelteKit live updates',
    ],
    order: 24,
    relatedDocs: [
      { href: '/docs/setup', label: 'Setup' },
      { href: '/docs/cli', label: 'CLI reference' },
      { href: '/docs/update-strategies', label: 'Update strategies' },
    ],
  },
  {
    slug: 'quasar-to-ios-android-with-capacitor',
    title: 'Ship iOS and Android apps from Quasar with Capacitor live updates',
    seoTitle: 'Quasar to iOS & Android with Capacitor + Live Updates (2026)',
    description:
      'Quasar has a Capacitor mode built in. Here is how to build native iOS and Android apps from your Quasar project and add over-the-air updates with OtaKit.',
    category: 'Tutorial',
    publishedAt: '2026-07-08',
    readingTime: '9 min read',
    keywords: [
      'Quasar mobile app',
      'Quasar Capacitor',
      'Quasar live updates',
      'Capacitor Quasar tutorial',
      'Quasar iOS Android',
      'Vue Quasar native app',
    ],
    order: 25,
    relatedDocs: [
      { href: '/docs/setup', label: 'Setup' },
      { href: '/docs/cli', label: 'CLI reference' },
      { href: '/docs/update-strategies', label: 'Update strategies' },
    ],
  },
  {
    slug: 'vite-app-to-ios-android-with-capacitor',
    title: 'Turn any Vite web app into iOS and Android apps with Capacitor',
    seoTitle: 'Vite App to iOS & Android with Capacitor (+ Live Updates) 2026',
    description:
      'A framework-agnostic guide: take any Vite-built web app to native iOS and Android with Capacitor, then push over-the-air updates with OtaKit. Works with vanilla JS, Solid, Preact, and more.',
    category: 'Tutorial',
    publishedAt: '2026-07-08',
    readingTime: '9 min read',
    keywords: [
      'Vite mobile app',
      'Vite Capacitor',
      'web app to native app',
      'Capacitor Vite tutorial',
      'vanilla JS mobile app',
      'Vite live updates',
    ],
    order: 26,
    relatedDocs: [
      { href: '/docs/setup', label: 'Setup' },
      { href: '/docs/cli', label: 'CLI reference' },
      { href: '/docs/update-strategies', label: 'Update strategies' },
    ],
  },
  {
    slug: 'pwa-to-native-app-with-capacitor',
    title: 'From PWA to native app: ship your PWA to the stores with Capacitor',
    seoTitle: 'PWA to Native App with Capacitor + Live Updates (2026)',
    description:
      'Your PWA already runs everywhere except the App Store. Capacitor wraps it as a native iOS and Android app you can submit, and OtaKit keeps it updated over the air like a PWA.',
    category: 'Tutorial',
    publishedAt: '2026-07-08',
    readingTime: '9 min read',
    keywords: [
      'PWA to native app',
      'PWA Capacitor',
      'PWA to App Store',
      'progressive web app iOS Android',
      'PWA native wrapper',
      'PWA live updates',
    ],
    order: 27,
    relatedDocs: [
      { href: '/docs/setup', label: 'Setup' },
      { href: '/docs/update-strategies', label: 'Update strategies' },
      { href: '/docs/cli', label: 'CLI reference' },
    ],
  },
  {
    slug: 'lovable-app-to-ios-android-with-capacitor',
    title: 'Ship your Lovable (AI-built) app to iOS and Android with Capacitor',
    seoTitle: 'Lovable App to iOS & Android with Capacitor + OTA (2026)',
    description:
      'Built an app with Lovable, v0, or Bolt? Export the code, wrap it with Capacitor for the App Store and Google Play, and iterate fast with OtaKit over-the-air updates.',
    category: 'Tutorial',
    publishedAt: '2026-07-08',
    readingTime: '9 min read',
    keywords: [
      'Lovable to native app',
      'Lovable mobile app',
      'AI app to iOS Android',
      'v0 Bolt Capacitor',
      'AI generated app store',
      'vibe coded app native',
    ],
    order: 28,
    relatedDocs: [
      { href: '/docs/setup', label: 'Setup' },
      { href: '/docs/react', label: 'React guide' },
      { href: '/docs/cli', label: 'CLI reference' },
    ],
  },
  {
    slug: 'ionic-live-updates-with-capacitor',
    title: 'Live updates for Ionic apps with Capacitor and OtaKit',
    seoTitle: 'Ionic Live Updates with Capacitor + OtaKit (2026 Guide)',
    description:
      'Ionic apps run on Capacitor, so they can update over the air. How to add live updates to an Ionic Angular, React, or Vue app with OtaKit — the affordable Appflow Live Updates alternative.',
    category: 'Tutorial',
    publishedAt: '2026-07-08',
    readingTime: '9 min read',
    keywords: [
      'Ionic live updates',
      'Ionic OTA updates',
      'Ionic Capacitor updates',
      'Appflow live updates alternative',
      'Ionic app store bypass',
      'Ionic deploy alternative',
    ],
    order: 29,
    relatedDocs: [
      { href: '/docs/setup', label: 'Setup' },
      { href: '/docs/update-strategies', label: 'Update strategies' },
      { href: '/docs/cli', label: 'CLI reference' },
    ],
  },
  {
    slug: 'how-to-test-capacitor-ota-updates',
    title: 'How to test Capacitor OTA updates before you ship them',
    seoTitle: 'How to Test Capacitor OTA Updates (2026 Guide)',
    description:
      'A repeatable way to test live updates on real devices before production: use a staging channel, verify activation and rollback, and catch native compatibility issues early with OtaKit.',
    category: 'Guides',
    publishedAt: '2026-07-08',
    readingTime: '9 min read',
    keywords: [
      'test OTA updates',
      'test Capacitor live updates',
      'staging channel updates',
      'QA mobile app updates',
      'verify OTA rollback',
      'preview live update',
    ],
    order: 30,
    relatedDocs: [
      { href: '/docs/channels', label: 'Channels & runtime version' },
      { href: '/docs/update-strategies', label: 'Update strategies' },
      { href: '/docs/cli', label: 'CLI reference' },
    ],
  },
  {
    slug: 'forced-and-mandatory-capacitor-updates',
    title: 'Forced and mandatory updates for Capacitor apps',
    seoTitle: 'Forced & Mandatory OTA Updates for Capacitor Apps (2026)',
    description:
      'Sometimes an update cannot wait for the next cold start. How to ship immediate, mandatory OTA updates in Capacitor with OtaKit using force-immediate releases and update policies.',
    category: 'Guides',
    publishedAt: '2026-07-08',
    readingTime: '8 min read',
    keywords: [
      'forced app update',
      'mandatory update mobile',
      'immediate OTA update',
      'force immediate update',
      'Capacitor update policy',
      'critical hotfix mobile',
    ],
    order: 31,
    relatedDocs: [
      { href: '/docs/update-strategies', label: 'Update strategies' },
      { href: '/docs/plugin', label: 'Plugin API' },
      { href: '/docs/events', label: 'Events' },
    ],
  },
  {
    slug: 'semantic-versioning-for-ota-bundles',
    title: 'Semantic versioning for OTA bundles and native runtimes',
    seoTitle: 'Semantic Versioning for Capacitor OTA Bundles (2026)',
    description:
      'How to version OTA bundles and keep them compatible with the native shells in the wild. A practical semver strategy for Capacitor live updates using runtime versions and channels.',
    category: 'Guides',
    publishedAt: '2026-07-08',
    readingTime: '8 min read',
    keywords: [
      'semantic versioning mobile app',
      'OTA bundle version',
      'runtime version Capacitor',
      'app version management',
      'native compatibility updates',
      'versioning live updates',
    ],
    order: 32,
    relatedDocs: [
      { href: '/docs/channels', label: 'Channels & runtime version' },
      { href: '/docs/plugin', label: 'Plugin API' },
      { href: '/docs/update-strategies', label: 'Update strategies' },
    ],
  },
  {
    slug: 'capacitor-ota-rollback-strategies',
    title: 'Rollback strategies for Capacitor OTA updates',
    seoTitle: 'Capacitor OTA Rollback Strategies That Actually Work (2026)',
    description:
      'Automatic rollback, manual rollback, and channel roll-forward: the three ways to recover from a bad live update in Capacitor, when to use each, and how OtaKit makes a broken release a non-event.',
    category: 'Guides',
    publishedAt: '2026-07-08',
    readingTime: '9 min read',
    keywords: [
      'OTA rollback',
      'app update rollback',
      'automatic rollback mobile',
      'roll back live update',
      'Capacitor update recovery',
      'notifyAppReady rollback',
    ],
    order: 33,
    relatedDocs: [
      { href: '/docs/update-strategies', label: 'Update strategies' },
      { href: '/docs/plugin', label: 'Plugin API' },
      { href: '/docs/channels', label: 'Channels & runtime version' },
    ],
  },
  {
    slug: 'background-vs-foreground-app-updates',
    title: 'Background vs foreground app updates: which UX should you pick?',
    seoTitle: 'Background vs Foreground OTA Update UX for Capacitor (2026)',
    description:
      'Silent background updates on next launch, or a restart-to-update prompt? The tradeoffs of each OTA update UX and how to configure both with OtaKit launch and resume policies.',
    category: 'Guides',
    publishedAt: '2026-07-08',
    readingTime: '8 min read',
    keywords: [
      'background app updates',
      'silent OTA update',
      'restart to update prompt',
      'update UX mobile app',
      'Capacitor launch policy',
      'foreground update',
    ],
    order: 34,
    relatedDocs: [
      { href: '/docs/update-strategies', label: 'Update strategies' },
      { href: '/docs/events', label: 'Events' },
      { href: '/docs/plugin', label: 'Plugin API' },
    ],
  },
  {
    slug: 'delta-updates-explained-capacitor',
    title: 'Delta updates explained: download only what changed',
    seoTitle: 'Delta Updates for Capacitor Apps, Explained (2026)',
    description:
      'For asset-heavy apps, full-bundle updates waste bandwidth on files that never changed. How delta updates work, when they matter, and how to enable them in OtaKit with one flag.',
    category: 'Guides',
    publishedAt: '2026-07-08',
    readingTime: '8 min read',
    keywords: [
      'delta updates',
      'differential updates mobile',
      'partial app update',
      'reduce update size',
      'Capacitor delta update',
      'incremental OTA',
    ],
    order: 35,
    relatedDocs: [
      { href: '/docs/update-strategies', label: 'Update strategies' },
      { href: '/docs/cli', label: 'CLI reference' },
      { href: '/docs/plugin', label: 'Plugin API' },
    ],
  },
  {
    slug: 'github-actions-ios-build-signing',
    title: 'Build and sign a Capacitor iOS app in GitHub Actions',
    seoTitle: 'GitHub Actions iOS Build with Signing for Capacitor (2026)',
    description:
      'A complete GitHub Actions workflow to build, sign, and upload a Capacitor iOS app — certificates, provisioning profiles, and the secrets setup — plus shipping the web layer with OtaKit.',
    category: 'Guides',
    publishedAt: '2026-07-08',
    readingTime: '11 min read',
    keywords: [
      'GitHub Actions iOS build',
      'iOS build certificate CI',
      'Capacitor iOS GitHub Actions',
      'provisioning profile CI',
      'sign iOS app CI',
      'fastlane match GitHub Actions',
    ],
    order: 36,
    relatedDocs: [
      { href: '/docs/ci', label: 'CI automation' },
      { href: '/docs/cli', label: 'CLI reference' },
      { href: '/docs/setup', label: 'Setup' },
    ],
  },
  {
    slug: 'github-actions-android-build-capacitor',
    title: 'Build and release a Capacitor Android app with GitHub Actions',
    seoTitle: 'GitHub Actions Android Build for Capacitor Apps (2026)',
    description:
      'Automate your Capacitor Android builds: a GitHub Actions workflow that assembles a signed AAB, handles the keystore securely, and ships web-layer updates with OtaKit.',
    category: 'Guides',
    publishedAt: '2026-07-08',
    readingTime: '10 min read',
    keywords: [
      'GitHub Actions Android build',
      'Capacitor Android CI',
      'sign Android AAB CI',
      'keystore GitHub Actions',
      'Android build automation',
      'Capacitor GitHub Actions',
    ],
    order: 37,
    relatedDocs: [
      { href: '/docs/ci', label: 'CI automation' },
      { href: '/docs/cli', label: 'CLI reference' },
      { href: '/docs/setup', label: 'Setup' },
    ],
  },
  {
    slug: 'gitlab-ci-capacitor-live-updates',
    title: 'Automate Capacitor live updates with GitLab CI/CD',
    seoTitle: 'GitLab CI/CD for Capacitor Live Updates (2026)',
    description:
      'A copy-paste .gitlab-ci.yml that builds your web app and releases an OTA bundle with the OtaKit CLI on every pipeline — the GitLab equivalent of the GitHub Actions flow.',
    category: 'Guides',
    publishedAt: '2026-07-08',
    readingTime: '8 min read',
    keywords: [
      'GitLab CI Capacitor',
      'GitLab CI/CD mobile app',
      'automate live updates GitLab',
      'gitlab-ci.yml Capacitor',
      'OtaKit GitLab',
      'CI CD OTA GitLab',
    ],
    order: 38,
    relatedDocs: [
      { href: '/docs/ci', label: 'CI automation' },
      { href: '/docs/cli', label: 'CLI reference' },
      { href: '/docs/channels', label: 'Channels & runtime version' },
    ],
  },
  {
    slug: 'fastlane-capacitor-ota-releases',
    title: 'Fastlane + OtaKit: automate store builds and OTA releases together',
    seoTitle: 'Fastlane + Capacitor OTA Releases with OtaKit (2026)',
    description:
      'Use Fastlane for the native store builds and OtaKit for the web-layer updates in between. How to combine both in one release lane so store submissions and live updates share a pipeline.',
    category: 'Guides',
    publishedAt: '2026-07-08',
    readingTime: '9 min read',
    keywords: [
      'Fastlane Capacitor',
      'Fastlane OTA updates',
      'Fastlane lane mobile app',
      'automate store submission',
      'Fastlane live updates',
      'Capacitor release lane',
    ],
    order: 39,
    relatedDocs: [
      { href: '/docs/ci', label: 'CI automation' },
      { href: '/docs/cli', label: 'CLI reference' },
      { href: '/docs/update-strategies', label: 'Update strategies' },
    ],
  },
  {
    slug: 'automate-channel-promotion-ota',
    title: 'Automate channel promotion for safe OTA releases',
    seoTitle: 'Automate OTA Channel Promotion (Beta to Production) 2026',
    description:
      'Promote the exact bundle you validated from beta to production automatically — on a schedule, a tag, or a manual approval gate. Channel-promotion patterns for Capacitor live updates with OtaKit.',
    category: 'Guides',
    publishedAt: '2026-07-08',
    readingTime: '8 min read',
    keywords: [
      'channel promotion',
      'promote beta to production',
      'OTA release pipeline',
      'approval gate mobile release',
      'Capacitor channel automation',
      'progressive delivery CI',
    ],
    order: 40,
    relatedDocs: [
      { href: '/docs/channels', label: 'Channels & runtime version' },
      { href: '/docs/ci', label: 'CI automation' },
      { href: '/docs/cli', label: 'CLI reference' },
    ],
  },
  {
    slug: 'apple-guideline-2-5-2-explained',
    title: 'Apple guideline 2.5.2 explained for OTA updates',
    seoTitle: 'Apple Guideline 2.5.2 Explained for OTA Updates (2026)',
    description:
      'The exact wording of App Store Review Guideline 2.5.2, the WebKit/JavaScriptCore exception it grants, and what it means in practice for Capacitor apps shipping over-the-air updates.',
    category: 'Compliance',
    publishedAt: '2026-07-08',
    readingTime: '9 min read',
    keywords: [
      'guideline 2.5.2',
      'Apple 2.5.2 OTA',
      'App Store executable code rule',
      'Apple 3.3.1 interpreted code',
      'App Store OTA compliance',
      'WebKit JavaScriptCore exception',
    ],
    order: 41,
    relatedDocs: [
      { href: '/docs/update-strategies', label: 'Update strategies' },
      { href: '/docs/security', label: 'Security' },
      { href: '/docs/setup', label: 'Setup' },
    ],
  },
  {
    slug: 'google-play-ota-compliance-checklist',
    title: 'Google Play OTA compliance: a developer checklist',
    seoTitle: 'Google Play OTA Update Compliance Checklist (2026)',
    description:
      "What Google Play's Device and Network Abuse policy actually restricts, why interpreted web-layer updates stay within policy, and a checklist to keep your Capacitor OTA setup compliant.",
    category: 'Compliance',
    publishedAt: '2026-07-08',
    readingTime: '8 min read',
    keywords: [
      'Google Play OTA policy',
      'Google Play compliance checklist',
      'device and network abuse policy',
      'Android OTA updates rules',
      'Google Play executable code',
      'Capacitor Google Play compliance',
    ],
    order: 42,
    relatedDocs: [
      { href: '/docs/update-strategies', label: 'Update strategies' },
      { href: '/docs/security', label: 'Security' },
      { href: '/docs/setup', label: 'Setup' },
    ],
  },
  {
    slug: 'ios-privacy-manifest-for-capacitor',
    title: 'The iOS privacy manifest for Capacitor apps, explained',
    seoTitle: 'iOS Privacy Manifest for Capacitor Apps (2026 Guide)',
    description:
      "Apple's privacy manifest and required-reason APIs are now mandatory. What a Capacitor app needs in its PrivacyInfo.xcprivacy, how plugins factor in, and common submission errors to avoid.",
    category: 'Compliance',
    publishedAt: '2026-07-08',
    readingTime: '9 min read',
    keywords: [
      'iOS privacy manifest',
      'PrivacyInfo.xcprivacy',
      'required reason API',
      'Capacitor privacy manifest',
      'Apple privacy requirements',
      'app privacy report',
    ],
    order: 43,
    relatedDocs: [
      { href: '/docs/setup', label: 'Setup' },
      { href: '/docs/plugin', label: 'Plugin API' },
      { href: '/docs/security', label: 'Security' },
    ],
  },
  {
    slug: 'first-app-store-review-guide',
    title: 'Passing your first App Store and Google Play review',
    seoTitle: 'Your First App Store & Google Play Review Guide (2026)',
    description:
      'The most common reasons first submissions get rejected, a pre-submission checklist for Capacitor apps, and how OTA updates let you fix post-launch issues without waiting on another review.',
    category: 'Compliance',
    publishedAt: '2026-07-08',
    readingTime: '10 min read',
    keywords: [
      'first app store review',
      'app store rejection reasons',
      'app review checklist',
      'submit app to App Store',
      'Google Play review guide',
      'Capacitor app submission',
    ],
    order: 44,
    relatedDocs: [
      { href: '/docs/setup', label: 'Setup' },
      { href: '/docs/update-strategies', label: 'Update strategies' },
      { href: '/docs/security', label: 'Security' },
    ],
  },
  {
    slug: 'capacitor-vs-appflow',
    title: 'Capacitor + OtaKit vs Ionic Appflow for live updates',
    seoTitle: 'Capacitor OTA vs Ionic Appflow: Live Updates Compared (2026)',
    description:
      'Ionic Appflow bundles live updates into a broader paid platform. A focused comparison of Appflow live updates vs OtaKit on price, delivery, rollback, encryption, and lock-in.',
    category: 'Comparison',
    publishedAt: '2026-07-08',
    readingTime: '9 min read',
    keywords: [
      'Capacitor vs Appflow',
      'Appflow live updates',
      'Ionic Appflow comparison',
      'Appflow pricing',
      'Appflow vs OtaKit',
      'Appflow deploy alternative',
    ],
    order: 45,
    relatedDocs: [
      { href: '/docs/setup', label: 'Setup' },
      { href: '/docs/cli', label: 'CLI reference' },
      { href: '/docs/update-strategies', label: 'Update strategies' },
    ],
  },
  {
    slug: 'ionic-appflow-alternative',
    title: 'The best Ionic Appflow alternative for live updates',
    seoTitle: 'Ionic Appflow Alternative: Cheaper Live Updates (2026)',
    description:
      'Looking for an Appflow alternative for live updates? OtaKit ships the same OTA capability with no per-seat platform pricing, CDN-direct delivery, delta updates, and an open-source stack.',
    category: 'Comparison',
    publishedAt: '2026-07-08',
    readingTime: '7 min read',
    keywords: [
      'Appflow alternative',
      'Ionic Appflow alternative',
      'Appflow live updates alternative',
      'Ionic deploy alternative',
      'cheaper than Appflow',
      'Capacitor OTA service',
    ],
    order: 46,
    relatedDocs: [
      { href: '/docs/setup', label: 'Setup' },
      { href: '/docs/cli', label: 'CLI reference' },
      { href: '/docs/security', label: 'Security' },
    ],
  },
  {
    slug: 'best-ota-tools-for-capacitor-2026',
    title: 'The best OTA update tools for Capacitor in 2026',
    seoTitle: 'Best OTA / Live Update Tools for Capacitor (2026)',
    description:
      'A buyer-focused roundup of live update tools for Capacitor apps — OtaKit, Capgo, Capawesome, and Appflow — compared on pricing model, delivery, security, and self-hosting.',
    category: 'Comparison',
    publishedAt: '2026-07-08',
    readingTime: '10 min read',
    keywords: [
      'best OTA tools Capacitor',
      'live update tools 2026',
      'Capacitor update service comparison',
      'OTA provider comparison',
      'mobile app update tools',
      'Capacitor live update options',
    ],
    order: 47,
    relatedDocs: [
      { href: '/docs/channels', label: 'Channels & runtime version' },
      { href: '/docs/cli', label: 'CLI reference' },
      { href: '/docs/security', label: 'Security' },
    ],
  },
  {
    slug: 'eas-update-vs-capacitor-ota',
    title: 'EAS Update vs Capacitor OTA: which live-update path fits you?',
    seoTitle: 'EAS Update vs Capacitor OTA Updates Compared (2026)',
    description:
      "Expo's EAS Update serves React Native; Capacitor OTA serves web-layer apps. A comparison of the two live-update models, their ecosystems, and how to choose based on your stack.",
    category: 'Comparison',
    publishedAt: '2026-07-08',
    readingTime: '9 min read',
    keywords: [
      'EAS Update vs Capacitor',
      'Expo Updates alternative',
      'EAS Update comparison',
      'React Native vs Capacitor updates',
      'live update ecosystems',
      'Capacitor OTA vs Expo',
    ],
    order: 48,
    relatedDocs: [
      { href: '/docs/setup', label: 'Setup' },
      { href: '/docs/update-strategies', label: 'Update strategies' },
      { href: '/docs/cli', label: 'CLI reference' },
    ],
  },
  {
    slug: 'capgo-vs-capawesome',
    title: 'Capgo vs Capawesome vs OtaKit: an honest 2026 comparison',
    seoTitle: 'Capgo vs Capawesome vs OtaKit: Honest Comparison (2026)',
    description:
      'The two best-known Capacitor live-update tools compared head to head on pricing, MAU metering, features, and open-source stance — with OtaKit as the no-metering third option.',
    category: 'Comparison',
    publishedAt: '2026-07-08',
    readingTime: '9 min read',
    keywords: [
      'Capgo vs Capawesome',
      'Capawesome vs Capgo',
      'Capacitor live update comparison',
      'Capgo pricing',
      'Capawesome pricing',
      'OtaKit comparison',
    ],
    order: 49,
    relatedDocs: [
      { href: '/docs/channels', label: 'Channels & runtime version' },
      { href: '/docs/cli', label: 'CLI reference' },
      { href: '/docs/security', label: 'Security' },
    ],
  },
  {
    slug: 'reduce-capacitor-app-bundle-size',
    title: 'How to reduce your Capacitor app bundle size',
    seoTitle: 'How to Reduce Capacitor App Bundle Size (2026)',
    description:
      'Smaller bundles mean faster startups and faster OTA updates. Practical ways to shrink a Capacitor web bundle — code splitting, asset optimization, tree shaking — and why delta updates finish the job.',
    category: 'Guides',
    publishedAt: '2026-07-08',
    readingTime: '9 min read',
    keywords: [
      'reduce app bundle size',
      'Capacitor bundle size',
      'optimize web bundle',
      'code splitting mobile app',
      'smaller OTA updates',
      'app performance bundle',
    ],
    order: 50,
    relatedDocs: [
      { href: '/docs/update-strategies', label: 'Update strategies' },
      { href: '/docs/cli', label: 'CLI reference' },
      { href: '/docs/plugin', label: 'Plugin API' },
    ],
  },
  {
    slug: 'feature-flags-in-capacitor-apps',
    title: 'Feature flags in Capacitor apps with OTA updates',
    seoTitle: 'Feature Flags in Capacitor Apps with OTA Updates (2026)',
    description:
      'Combine feature flags with over-the-air updates to ship dark, flip features on remotely, and run controlled rollouts — without a store release. Patterns for Capacitor apps using OtaKit channels.',
    category: 'Guides',
    publishedAt: '2026-07-08',
    readingTime: '8 min read',
    keywords: [
      'feature flags mobile app',
      'feature flags Capacitor',
      'remote config mobile',
      'ship dark feature flag',
      'controlled rollout flags',
      'OTA feature toggle',
    ],
    order: 51,
    relatedDocs: [
      { href: '/docs/channels', label: 'Channels & runtime version' },
      { href: '/docs/update-strategies', label: 'Update strategies' },
      { href: '/docs/events', label: 'Events' },
    ],
  },
  {
    slug: 'ionic-appflow-is-shutting-down',
    title: 'Ionic Appflow is shutting down: what to do next',
    seoTitle: 'Ionic Appflow Shutting Down: Migration Options (2026)',
    description:
      'Ionic Appflow is being wound down. Here is what the shutdown means for your live updates and native builds, your realistic migration options, and how to move to OtaKit without a rebuild.',
    category: 'Migration',
    publishedAt: '2026-07-09',
    readingTime: '9 min read',
    keywords: [
      'Ionic Appflow shutdown',
      'Appflow end of life',
      'Appflow alternative',
      'Appflow migration',
      'Ionic deploy shutdown',
      'Capacitor live updates',
    ],
    order: 52,
    featured: true,
    relatedDocs: [
      { href: '/docs/setup', label: 'Setup' },
      { href: '/docs/cli', label: 'CLI reference' },
      { href: '/docs/update-strategies', label: 'Update strategies' },
    ],
  },
  {
    slug: 'migrate-from-app-center-to-otakit',
    title: 'Microsoft App Center is gone: migrating to OtaKit',
    seoTitle: 'Migrate From App Center to OtaKit (Capacitor OTA) 2026',
    description:
      'Microsoft retired App Center, taking CodePush distribution with it. A practical migration path from App Center to OtaKit for Capacitor live updates, with the config and API mapping.',
    category: 'Migration',
    publishedAt: '2026-07-09',
    readingTime: '8 min read',
    keywords: [
      'App Center alternative',
      'App Center shutdown',
      'CodePush App Center migration',
      'App Center Capacitor',
      'migrate from App Center',
      'live update service',
    ],
    order: 53,
    relatedDocs: [
      { href: '/docs/setup', label: 'Setup' },
      { href: '/docs/cli', label: 'CLI reference' },
      { href: '/docs/security', label: 'Security' },
    ],
  },
  {
    slug: 'voltbuilder-alternative',
    title: 'The VoltBuilder alternative for Capacitor builds and live updates',
    seoTitle: 'VoltBuilder Alternative for Capacitor + Live Updates (2026)',
    description:
      'VoltBuilder compiles your web app into native binaries in the cloud, but it does not do over-the-air updates. How OtaKit adds instant live updates to that workflow, and where each tool fits.',
    category: 'Comparison',
    publishedAt: '2026-07-09',
    readingTime: '7 min read',
    keywords: [
      'VoltBuilder alternative',
      'VoltBuilder live updates',
      'cloud build Capacitor',
      'VoltBuilder vs Capgo',
      'Capacitor OTA updates',
      'web to native build',
    ],
    order: 54,
    relatedDocs: [
      { href: '/docs/setup', label: 'Setup' },
      { href: '/docs/ci', label: 'CI automation' },
      { href: '/docs/cli', label: 'CLI reference' },
    ],
  },
  {
    slug: 'self-hosted-capacitor-live-updates',
    title: 'Self-hosted live updates for Capacitor apps',
    seoTitle: 'Self-Hosted Capacitor Live Updates (Open Source) 2026',
    description:
      'Own your update infrastructure end to end. How to self-host Capacitor live updates with OtaKit — a fully MIT-licensed stack, static CDN delivery, and no per-device metering or vendor lock-in.',
    category: 'Guides',
    publishedAt: '2026-07-09',
    readingTime: '9 min read',
    keywords: [
      'self-hosted live updates',
      'self-hosted OTA Capacitor',
      'open source live updates',
      'host your own update server',
      'self-host Capgo alternative',
      'MIT licensed OTA',
    ],
    order: 55,
    relatedDocs: [
      { href: '/docs/self-host', label: 'Self-hosting' },
      { href: '/docs/setup', label: 'Setup' },
      { href: '/docs/security', label: 'Security' },
    ],
  },
  {
    slug: 'open-source-vs-proprietary-ota-updates',
    title: 'Open source vs proprietary OTA update tools',
    seoTitle: 'Open Source vs Proprietary OTA Update Tools (2026)',
    description:
      'Live update tools split into open-source and closed SaaS. What each choice means for lock-in, cost, auditability, and self-hosting — and why OtaKit ships a fully MIT stack.',
    category: 'Comparison',
    publishedAt: '2026-07-09',
    readingTime: '8 min read',
    keywords: [
      'open source OTA updates',
      'open source vs proprietary',
      'open source live updates',
      'vendor lock-in mobile updates',
      'MIT licensed live updates',
      'self-hostable OTA',
    ],
    order: 56,
    relatedDocs: [
      { href: '/docs/self-host', label: 'Self-hosting' },
      { href: '/docs/security', label: 'Security' },
      { href: '/docs/setup', label: 'Setup' },
    ],
  },
  {
    slug: 'migrate-cordova-to-capacitor',
    title: 'Migrating from Cordova to Capacitor in 2026',
    seoTitle: 'Migrate From Cordova to Capacitor: Complete Guide (2026)',
    description:
      'Cordova is in maintenance mode. A step-by-step guide to migrating a Cordova app to Capacitor without a rewrite — plugins, config, native projects — and adding OTA live updates Cordova never had.',
    category: 'Migration',
    publishedAt: '2026-07-10',
    readingTime: '11 min read',
    keywords: [
      'Cordova to Capacitor migration',
      'migrate Cordova to Capacitor',
      'Cordova alternative',
      'Capacitor migration guide',
      'Cordova end of life',
      'Cordova live updates',
    ],
    order: 57,
    relatedDocs: [
      { href: '/docs/setup', label: 'Setup' },
      { href: '/docs/cli', label: 'CLI reference' },
      { href: '/docs/update-strategies', label: 'Update strategies' },
    ],
  },
  {
    slug: 'capacitor-ota-hosting-options-compared',
    title: 'Where to host Capacitor OTA updates: your options compared',
    seoTitle: 'Capacitor OTA Update Hosting Options Compared (2026)',
    description:
      'Managed service, self-hosted server, or roll-your-own on a CDN? The real tradeoffs of each way to host Capacitor OTA updates on cost, reliability, and maintenance — with OtaKit as the static-CDN option.',
    category: 'Comparison',
    publishedAt: '2026-07-10',
    readingTime: '9 min read',
    keywords: [
      'Capacitor OTA hosting',
      'host live updates',
      'OTA update server',
      'self-host vs managed OTA',
      'CDN live updates',
      'update hosting comparison',
    ],
    order: 58,
    relatedDocs: [
      { href: '/docs/self-host', label: 'Self-hosting' },
      { href: '/docs/setup', label: 'Setup' },
      { href: '/docs/security', label: 'Security' },
    ],
  },
  {
    slug: 'monitor-capacitor-ota-updates',
    title: 'How to monitor Capacitor OTA update success',
    seoTitle: 'Monitor Capacitor OTA Update Success (2026 Guide)',
    description:
      'An update you cannot see is an update you cannot trust. How to monitor Capacitor live updates in production — download and apply events, failure signals, and the metrics that should gate a rollout.',
    category: 'Guides',
    publishedAt: '2026-07-10',
    readingTime: '9 min read',
    keywords: [
      'monitor OTA updates',
      'track live update success',
      'OTA update metrics',
      'Capacitor update monitoring',
      'update failure rate',
      'live update observability',
    ],
    order: 59,
    relatedDocs: [
      { href: '/docs/events', label: 'Events' },
      { href: '/docs/plugin', label: 'Plugin API' },
      { href: '/docs/update-strategies', label: 'Update strategies' },
    ],
  },
  {
    slug: 'schedule-capacitor-ota-updates',
    title: 'How to schedule Capacitor OTA updates',
    seoTitle: 'How to Schedule Capacitor OTA Updates (2026)',
    description:
      'Ship on your timeline, not at merge time. How to schedule Capacitor live updates with channel promotion, CI cron jobs, and approval gates so releases go out at the right moment.',
    category: 'Guides',
    publishedAt: '2026-07-10',
    readingTime: '8 min read',
    keywords: [
      'schedule OTA updates',
      'scheduled app updates',
      'timed live update release',
      'Capacitor update scheduling',
      'channel promotion schedule',
      'CI cron mobile release',
    ],
    order: 60,
    relatedDocs: [
      { href: '/docs/channels', label: 'Channels & runtime version' },
      { href: '/docs/ci', label: 'CI automation' },
      { href: '/docs/cli', label: 'CLI reference' },
    ],
  },
  {
    slug: 'debug-capacitor-ota-updates',
    title: 'Debugging Capacitor OTA updates: a practical checklist',
    seoTitle: 'Debug Capacitor OTA Updates: Troubleshooting Guide (2026)',
    description:
      'Your update did not land — now what? A systematic checklist for debugging Capacitor live updates: notifyAppReady, runtime version mismatches, manifest errors, channel config, and rollback loops.',
    category: 'Guides',
    publishedAt: '2026-07-10',
    readingTime: '10 min read',
    keywords: [
      'debug OTA updates',
      'Capacitor update not working',
      'live update troubleshooting',
      'notifyAppReady not called',
      'OTA update failed',
      'update debugging checklist',
    ],
    order: 61,
    relatedDocs: [
      { href: '/docs/plugin', label: 'Plugin API' },
      { href: '/docs/events', label: 'Events' },
      { href: '/docs/channels', label: 'Channels & runtime version' },
    ],
  },
  {
    slug: 'target-ota-updates-to-specific-users',
    title: 'Send an OTA update to specific users or groups',
    seoTitle: 'Target OTA Updates to Specific Users or Groups (2026)',
    description:
      'Not every update should reach everyone at once. How to target Capacitor live updates to specific users, beta groups, or cohorts using channels and runtime versions with OtaKit.',
    category: 'Guides',
    publishedAt: '2026-07-11',
    readingTime: '8 min read',
    keywords: [
      'target app updates',
      'send update to specific users',
      'user targeting OTA',
      'beta group updates',
      'cohort live updates',
      'Capacitor channel targeting',
    ],
    order: 62,
    relatedDocs: [
      { href: '/docs/channels', label: 'Channels & runtime version' },
      { href: '/docs/plugin', label: 'Plugin API' },
      { href: '/docs/update-strategies', label: 'Update strategies' },
    ],
  },
  {
    slug: 'ab-testing-capacitor-live-updates',
    title: 'A/B testing Capacitor apps with live update channels',
    seoTitle: 'A/B Testing Capacitor Apps with Live Updates (2026)',
    description:
      'Run real experiments in production without a store release. How to A/B test Capacitor apps using live update channels and feature flags, measure the result, and promote the winner with OtaKit.',
    category: 'Guides',
    publishedAt: '2026-07-11',
    readingTime: '9 min read',
    keywords: [
      'A/B testing mobile app',
      'A/B test Capacitor',
      'experiment live updates',
      'split testing mobile',
      'feature flag A/B test',
      'channel A/B testing',
    ],
    order: 63,
    relatedDocs: [
      { href: '/docs/channels', label: 'Channels & runtime version' },
      { href: '/docs/update-strategies', label: 'Update strategies' },
      { href: '/docs/events', label: 'Events' },
    ],
  },
  {
    slug: 'deploy-hotfixes-capacitor-ota',
    title: 'Deploy a hotfix to your Capacitor app in minutes',
    seoTitle: 'Deploy a Capacitor App Hotfix in Minutes with OTA (2026)',
    description:
      'A critical bug is live and the next store review is days away. How to ship an emergency hotfix to your Capacitor app over the air with a force-immediate OTA release — no store queue.',
    category: 'Guides',
    publishedAt: '2026-07-11',
    readingTime: '8 min read',
    keywords: [
      'mobile app hotfix',
      'deploy hotfix Capacitor',
      'emergency app update',
      'force immediate update',
      'critical bug fix mobile',
      'hotfix without store review',
    ],
    order: 64,
    relatedDocs: [
      { href: '/docs/update-strategies', label: 'Update strategies' },
      { href: '/docs/plugin', label: 'Plugin API' },
      { href: '/docs/cli', label: 'CLI reference' },
    ],
  },
  {
    slug: 'ota-update-error-handling-ux',
    title: 'Error handling and update UX for Capacitor live updates',
    seoTitle: 'OTA Update Error Handling & UX for Capacitor (2026)',
    description:
      'A failed update should be invisible to users, not a broken app. How to handle live update errors gracefully in Capacitor — retries, silent rollback, and the UX patterns that keep users unaffected.',
    category: 'Guides',
    publishedAt: '2026-07-11',
    readingTime: '8 min read',
    keywords: [
      'app update error handling',
      'OTA update failure UX',
      'live update retry',
      'graceful update failure',
      'Capacitor update errors',
      'update rollback UX',
    ],
    order: 65,
    relatedDocs: [
      { href: '/docs/events', label: 'Events' },
      { href: '/docs/plugin', label: 'Plugin API' },
      { href: '/docs/update-strategies', label: 'Update strategies' },
    ],
  },
  {
    slug: 'npm-scripts-for-capacitor-ota',
    title: 'npm scripts for Capacitor OTA releases',
    seoTitle: 'npm Scripts for Capacitor OTA Releases (2026)',
    description:
      'Wrap the release flow in package.json so shipping an update is one command everyone on the team knows. Copy-paste npm scripts for building and releasing Capacitor OTA bundles with the OtaKit CLI.',
    category: 'Guides',
    publishedAt: '2026-07-12',
    readingTime: '7 min read',
    keywords: [
      'npm scripts Capacitor',
      'package.json OTA release',
      'Capacitor release script',
      'automate live update npm',
      'OtaKit CLI scripts',
      'npm run release mobile',
    ],
    order: 66,
    relatedDocs: [
      { href: '/docs/cli', label: 'CLI reference' },
      { href: '/docs/ci', label: 'CI automation' },
      { href: '/docs/channels', label: 'Channels & runtime version' },
    ],
  },
  {
    slug: 'staging-environments-capacitor-channels',
    title: 'Staging environments with Capacitor update channels',
    seoTitle: 'Staging Environments with Capacitor Channels (2026)',
    description:
      'One app ID, many environments. How to run dev, staging, and production for a Capacitor app using update channels — validate a bundle on staging, then promote the exact same build to production.',
    category: 'Guides',
    publishedAt: '2026-07-12',
    readingTime: '8 min read',
    keywords: [
      'staging environment Capacitor',
      'dev staging production channels',
      'Capacitor environments',
      'staging live updates',
      'promote staging to production',
      'update channels staging',
    ],
    order: 67,
    relatedDocs: [
      { href: '/docs/channels', label: 'Channels & runtime version' },
      { href: '/docs/update-strategies', label: 'Update strategies' },
      { href: '/docs/ci', label: 'CI automation' },
    ],
  },
  {
    slug: 'platform-specific-ota-updates',
    title: 'Targeting iOS vs Android with OTA updates',
    seoTitle: 'Platform-Specific OTA Updates: iOS vs Android (2026)',
    description:
      'Sometimes a fix only applies to one platform. When and how to ship platform-specific Capacitor live updates for iOS and Android separately using channels and runtime versions.',
    category: 'Guides',
    publishedAt: '2026-07-12',
    readingTime: '7 min read',
    keywords: [
      'platform specific update',
      'iOS Android separate update',
      'target iOS OTA',
      'target Android OTA',
      'per platform live update',
      'Capacitor platform channel',
    ],
    order: 68,
    relatedDocs: [
      { href: '/docs/channels', label: 'Channels & runtime version' },
      { href: '/docs/update-strategies', label: 'Update strategies' },
      { href: '/docs/plugin', label: 'Plugin API' },
    ],
  },
  {
    slug: 'mobile-app-update-strategy-checklist',
    title: 'A mobile app update strategy checklist',
    seoTitle: 'Mobile App Update Strategy Checklist (2026)',
    description:
      'A complete checklist for planning how your Capacitor app ships updates: cadence, channels, staged rollouts, rollback, versioning, and user communication — the operational playbook in one page.',
    category: 'Guides',
    publishedAt: '2026-07-12',
    readingTime: '9 min read',
    keywords: [
      'app update strategy',
      'mobile update checklist',
      'release strategy mobile app',
      'update cadence',
      'Capacitor release planning',
      'OTA update playbook',
    ],
    order: 69,
    relatedDocs: [
      { href: '/docs/update-strategies', label: 'Update strategies' },
      { href: '/docs/channels', label: 'Channels & runtime version' },
      { href: '/docs/ci', label: 'CI automation' },
    ],
  },
  {
    slug: 'capacitor-live-updates-faq',
    title: 'Capacitor live updates FAQ',
    seoTitle: 'Capacitor Live Updates FAQ: Your Questions Answered (2026)',
    description:
      'The questions developers actually ask about Capacitor live updates — are they allowed, what can you ship, how fast, how safe, how much they cost — answered in one place with links to the details.',
    category: 'Guides',
    publishedAt: '2026-07-13',
    readingTime: '10 min read',
    keywords: [
      'Capacitor live updates FAQ',
      'OTA updates questions',
      'live update FAQ',
      'are live updates allowed',
      'Capacitor OTA explained',
      'live updates how it works',
    ],
    order: 70,
    relatedDocs: [
      { href: '/docs/setup', label: 'Setup' },
      { href: '/docs/update-strategies', label: 'Update strategies' },
      { href: '/docs/security', label: 'Security' },
    ],
  },
  {
    slug: 'capacitor-push-notifications-firebase',
    title: 'Push notifications in Capacitor with Firebase',
    seoTitle: 'Capacitor Push Notifications with Firebase (2026 Guide)',
    description:
      'A complete guide to adding push notifications to a Capacitor app with Firebase Cloud Messaging — iOS and Android setup, permissions, tokens, and handling taps — plus shipping the JS side over the air.',
    category: 'Tutorial',
    publishedAt: '2026-07-13',
    readingTime: '11 min read',
    keywords: [
      'Capacitor push notifications',
      'Capacitor Firebase FCM',
      'push notifications Ionic',
      'FCM Capacitor setup',
      'iOS Android push Capacitor',
      'Capacitor notifications guide',
    ],
    order: 71,
    relatedDocs: [
      { href: '/docs/setup', label: 'Setup' },
      { href: '/docs/plugin', label: 'Plugin API' },
      { href: '/docs/update-strategies', label: 'Update strategies' },
    ],
  },
  {
    slug: 'capacitor-deep-links-universal-links',
    title: 'Deep links and universal links in Capacitor',
    seoTitle: 'Capacitor Deep Links & Universal Links Guide (2026)',
    description:
      'Make your Capacitor app open from URLs. How to set up deep links, iOS universal links, and Android app links — association files, intent filters, and routing — and tune the routing logic over the air.',
    category: 'Tutorial',
    publishedAt: '2026-07-13',
    readingTime: '10 min read',
    keywords: [
      'Capacitor deep links',
      'Capacitor universal links',
      'Android app links',
      'iOS universal links Capacitor',
      'deep linking mobile app',
      'Capacitor URL scheme',
    ],
    order: 72,
    relatedDocs: [
      { href: '/docs/setup', label: 'Setup' },
      { href: '/docs/plugin', label: 'Plugin API' },
      { href: '/docs/update-strategies', label: 'Update strategies' },
    ],
  },
  {
    slug: 'biometric-auth-capacitor',
    title: 'Biometric authentication in Capacitor apps',
    seoTitle: 'Biometric Authentication in Capacitor Apps (2026)',
    description:
      'Add Face ID, Touch ID, and Android biometric login to your Capacitor app. How biometric authentication works, how to store secrets safely behind it, and how OTA updates keep the flow current.',
    category: 'Tutorial',
    publishedAt: '2026-07-13',
    readingTime: '9 min read',
    keywords: [
      'Capacitor biometric authentication',
      'Face ID Capacitor',
      'Touch ID mobile app',
      'Android biometric login',
      'biometric auth Ionic',
      'fingerprint login Capacitor',
    ],
    order: 73,
    relatedDocs: [
      { href: '/docs/security', label: 'Security' },
      { href: '/docs/plugin', label: 'Plugin API' },
      { href: '/docs/setup', label: 'Setup' },
    ],
  },
  {
    slug: 'capacitor-social-login-oauth',
    title: 'Social login and OAuth2 in Capacitor apps',
    seoTitle: 'Capacitor Social Login & OAuth2 Guide (2026)',
    description:
      'Add Sign in with Apple, Google, and OAuth2 to a Capacitor app the native way, with Supabase as the backend. Setup, redirect handling, token storage, and iterating the flow with OTA updates.',
    category: 'Tutorial',
    publishedAt: '2026-07-14',
    readingTime: '10 min read',
    keywords: [
      'Capacitor social login',
      'Capacitor OAuth2',
      'Sign in with Apple Capacitor',
      'Google login Capacitor',
      'Supabase auth Capacitor',
      'OAuth mobile app',
    ],
    order: 74,
    relatedDocs: [
      { href: '/docs/security', label: 'Security' },
      { href: '/docs/plugin', label: 'Plugin API' },
      { href: '/docs/setup', label: 'Setup' },
    ],
  },
  {
    slug: 'secure-token-storage-capacitor',
    title: 'Secure token storage in Capacitor apps',
    seoTitle: 'Secure Token Storage in Capacitor Apps (2026)',
    description:
      'Where you keep auth tokens decides how secure your app really is. How to store tokens safely in Capacitor using the iOS Keychain and Android Keystore — not localStorage — and why it matters for OTA.',
    category: 'Guides',
    publishedAt: '2026-07-14',
    readingTime: '9 min read',
    keywords: [
      'secure token storage',
      'Capacitor secure storage',
      'iOS Keychain Capacitor',
      'Android Keystore mobile',
      'store auth token mobile',
      'token storage best practices',
    ],
    order: 75,
    relatedDocs: [
      { href: '/docs/security', label: 'Security' },
      { href: '/docs/plugin', label: 'Plugin API' },
      { href: '/docs/setup', label: 'Setup' },
    ],
  },
  {
    slug: 'capacitor-splash-screen-guide',
    title: 'Splash screens in Capacitor: the complete guide',
    seoTitle: 'Capacitor Splash Screen: Complete Setup Guide (2026)',
    description:
      'Configure a native splash screen for your Capacitor app on iOS and Android, control when it hides, and use that first moment to check for an OTA update before the user sees stale content.',
    category: 'Tutorial',
    publishedAt: '2026-07-14',
    readingTime: '8 min read',
    keywords: [
      'Capacitor splash screen',
      'splash screen iOS Android',
      'Capacitor launch screen',
      'hide splash screen Capacitor',
      'native splash Ionic',
      'app startup update check',
    ],
    order: 76,
    relatedDocs: [
      { href: '/docs/setup', label: 'Setup' },
      { href: '/docs/plugin', label: 'Plugin API' },
      { href: '/docs/update-strategies', label: 'Update strategies' },
    ],
  },
  {
    slug: 'capacitor-edge-to-edge-display',
    title: 'Edge-to-edge display in Capacitor without plugins',
    seoTitle: 'Capacitor Edge-to-Edge Display Without Plugins (2026)',
    description:
      'Android 15 makes edge-to-edge mandatory. How to handle edge-to-edge display and safe areas in a Capacitor app with native config and CSS env() — no extra plugin — and ship tweaks over the air.',
    category: 'Tutorial',
    publishedAt: '2026-07-14',
    readingTime: '8 min read',
    keywords: [
      'Capacitor edge to edge',
      'Android 15 edge to edge',
      'safe area Capacitor',
      'status bar Capacitor',
      'env safe area inset',
      'Capacitor full screen',
    ],
    order: 77,
    relatedDocs: [
      { href: '/docs/setup', label: 'Setup' },
      { href: '/docs/plugin', label: 'Plugin API' },
      { href: '/docs/update-strategies', label: 'Update strategies' },
    ],
  },
  {
    slug: 'capacitor-background-tasks',
    title: 'How background tasks work in Capacitor',
    seoTitle: 'Background Tasks in Capacitor: How They Work (2026)',
    description:
      'What Capacitor apps can and cannot do in the background on iOS and Android, how to run background fetch and tasks within OS limits, and how to check for an OTA update on resume.',
    category: 'Guides',
    publishedAt: '2026-07-15',
    readingTime: '9 min read',
    keywords: [
      'Capacitor background tasks',
      'background fetch Capacitor',
      'background mode mobile app',
      'iOS background execution',
      'Android background work',
      'Capacitor background runner',
    ],
    order: 78,
    relatedDocs: [
      { href: '/docs/plugin', label: 'Plugin API' },
      { href: '/docs/events', label: 'Events' },
      { href: '/docs/update-strategies', label: 'Update strategies' },
    ],
  },
  {
    slug: 'capacitor-in-app-purchases',
    title: 'In-app purchases in Capacitor (and making revenue)',
    seoTitle: 'Capacitor In-App Purchases: Setup & Revenue Guide (2026)',
    description:
      'Add subscriptions and in-app purchases to a Capacitor app with StoreKit and Google Play Billing, stay compliant with store rules, and iterate your paywall over the air to grow revenue.',
    category: 'Tutorial',
    publishedAt: '2026-07-15',
    readingTime: '11 min read',
    keywords: [
      'Capacitor in-app purchases',
      'Capacitor subscriptions',
      'StoreKit Capacitor',
      'Google Play Billing Capacitor',
      'mobile app revenue',
      'paywall Capacitor',
    ],
    order: 79,
    relatedDocs: [
      { href: '/docs/setup', label: 'Setup' },
      { href: '/docs/plugin', label: 'Plugin API' },
      { href: '/docs/update-strategies', label: 'Update strategies' },
    ],
  },
  {
    slug: 'capacitor-barcode-scanner',
    title: 'Building a barcode and QR scanner in Capacitor',
    seoTitle: 'Capacitor Barcode & QR Scanner: Build Guide (2026)',
    description:
      'Add fast, native barcode and QR code scanning to your Capacitor app, handle camera permissions cleanly, and ship scanning-flow changes over the air without a store release.',
    category: 'Tutorial',
    publishedAt: '2026-07-15',
    readingTime: '8 min read',
    keywords: [
      'Capacitor barcode scanner',
      'Capacitor QR scanner',
      'scan barcode mobile app',
      'camera permission Capacitor',
      'QR code Capacitor',
      'barcode scanning Ionic',
    ],
    order: 80,
    relatedDocs: [
      { href: '/docs/setup', label: 'Setup' },
      { href: '/docs/plugin', label: 'Plugin API' },
      { href: '/docs/update-strategies', label: 'Update strategies' },
    ],
  },
  {
    slug: 'capacitor-offline-support',
    title: 'Offline support and offline screens in Capacitor',
    seoTitle: 'Capacitor Offline Support: Detection & Screens (2026)',
    description:
      'Real apps lose the network. How to detect connectivity, cache the app shell, show a clean offline screen, and keep OTA updates working across connection drops in a Capacitor app.',
    category: 'Guides',
    publishedAt: '2026-07-15',
    readingTime: '8 min read',
    keywords: [
      'Capacitor offline mode',
      'offline screen Capacitor',
      'network detection Capacitor',
      'offline support mobile app',
      'Capacitor connectivity',
      'offline first Capacitor',
    ],
    order: 81,
    relatedDocs: [
      { href: '/docs/plugin', label: 'Plugin API' },
      { href: '/docs/events', label: 'Events' },
      { href: '/docs/update-strategies', label: 'Update strategies' },
    ],
  },
  {
    slug: 'fix-capacitor-agp-9-build-errors',
    title: 'Fix Capacitor plugin build errors with AGP 9',
    seoTitle: 'Fix Capacitor Plugin Build Errors with AGP 9 (2026)',
    description:
      'Android Gradle Plugin 9 breaks older Capacitor plugin builds with namespace and compileSdk errors. What actually fails, the exact fixes, and how to unblock your Android build fast.',
    category: 'Guides',
    publishedAt: '2026-07-16',
    readingTime: '8 min read',
    keywords: [
      'Capacitor AGP 9 error',
      'Android Gradle Plugin 9 Capacitor',
      'Capacitor build error namespace',
      'AGP 9 plugin fix',
      'Capacitor Android build fail',
      'compileSdk error Capacitor',
    ],
    order: 82,
    relatedDocs: [
      { href: '/docs/setup', label: 'Setup' },
      { href: '/docs/ci', label: 'CI automation' },
      { href: '/docs/update-strategies', label: 'Update strategies' },
    ],
  },
  {
    slug: 'android-16kb-page-size-capacitor',
    title: 'Android 16KB page size: find the problem Capacitor plugin',
    seoTitle: 'Android 16KB Page Size: Fix Capacitor Plugins (2026)',
    description:
      "Google Play now requires 16KB page-size support. How to detect which Capacitor plugin's native library breaks 16KB alignment, what to do about it, and how to verify the fix before you submit.",
    category: 'Guides',
    publishedAt: '2026-07-16',
    readingTime: '8 min read',
    keywords: [
      'Android 16KB page size',
      '16KB page size Capacitor',
      'Google Play 16KB requirement',
      'native library alignment',
      'Capacitor plugin 16KB',
      'page size Android 15',
    ],
    order: 83,
    relatedDocs: [
      { href: '/docs/setup', label: 'Setup' },
      { href: '/docs/ci', label: 'CI automation' },
      { href: '/docs/plugin', label: 'Plugin API' },
    ],
  },
  {
    slug: 'xcode-26-capacitor-requirement',
    title: "Apple's Xcode 26 requirement for Capacitor apps",
    seoTitle: 'Xcode 26 Requirement for Capacitor Apps Explained (2026)',
    description:
      'Apple now requires builds from a recent Xcode and SDK. What the Xcode 26 requirement means for Capacitor apps, what breaks in older setups, and how to update your local and CI builds.',
    category: 'Guides',
    publishedAt: '2026-07-16',
    readingTime: '7 min read',
    keywords: [
      'Xcode 26 requirement',
      'Xcode 26 Capacitor',
      'Apple SDK requirement',
      'iOS build Xcode version',
      'Capacitor iOS build update',
      'Xcode CI upgrade',
    ],
    order: 84,
    relatedDocs: [
      { href: '/docs/ci', label: 'CI automation' },
      { href: '/docs/setup', label: 'Setup' },
      { href: '/docs/update-strategies', label: 'Update strategies' },
    ],
  },
  {
    slug: 'fix-capacitor-version-mismatch',
    title: 'Fixing Capacitor version mismatch errors',
    seoTitle: 'Fix Capacitor Version Mismatch Errors (2026)',
    description:
      'Capacitor core, CLI, and plugins have to agree on a version. What triggers version mismatch errors, how to align @capacitor packages cleanly, and how it relates to your OTA runtime version.',
    category: 'Guides',
    publishedAt: '2026-07-16',
    readingTime: '7 min read',
    keywords: [
      'Capacitor version mismatch',
      'Capacitor plugin version error',
      'align Capacitor versions',
      '@capacitor/core version',
      'Capacitor CLI version error',
      'Capacitor dependency conflict',
    ],
    order: 85,
    relatedDocs: [
      { href: '/docs/setup', label: 'Setup' },
      { href: '/docs/channels', label: 'Channels & runtime version' },
      { href: '/docs/cli', label: 'CLI reference' },
    ],
  },
  {
    slug: 'fix-capacitor-android-build-errors',
    title: 'How to resolve Android build errors in Capacitor',
    seoTitle: 'Fix Capacitor Android Build Errors: Triage Guide (2026)',
    description:
      'Gradle failures, SDK mismatches, manifest merger conflicts, duplicate classes — the Android build errors that hit Capacitor apps most, and a repeatable way to diagnose and fix each one.',
    category: 'Guides',
    publishedAt: '2026-07-17',
    readingTime: '9 min read',
    keywords: [
      'Capacitor Android build error',
      'Gradle build failed Capacitor',
      'manifest merger error',
      'duplicate class Android',
      'Capacitor build troubleshooting',
      'Android SDK error Capacitor',
    ],
    order: 86,
    relatedDocs: [
      { href: '/docs/setup', label: 'Setup' },
      { href: '/docs/ci', label: 'CI automation' },
      { href: '/docs/plugin', label: 'Plugin API' },
    ],
  },
  {
    slug: 'capacitor-spm-migration',
    title: 'Migrating a Capacitor app to Swift Package Manager',
    seoTitle: 'Capacitor Swift Package Manager Migration Guide (2026)',
    description:
      'Capacitor is moving from CocoaPods to Swift Package Manager on iOS. Why the switch matters, how SPM compares to CocoaPods, and a step-by-step migration for your Capacitor iOS project.',
    category: 'Migration',
    publishedAt: '2026-07-17',
    readingTime: '9 min read',
    keywords: [
      'Capacitor Swift Package Manager',
      'Capacitor SPM migration',
      'SPM vs CocoaPods Capacitor',
      'migrate Capacitor to SPM',
      'Capacitor iOS SPM',
      'CocoaPods to SPM',
    ],
    order: 87,
    relatedDocs: [
      { href: '/docs/setup', label: 'Setup' },
      { href: '/docs/ci', label: 'CI automation' },
      { href: '/docs/plugin', label: 'Plugin API' },
    ],
  },
  {
    slug: 'capacitor-cli-commands-guide',
    title: 'Capacitor CLI commands: the practical guide',
    seoTitle: 'Capacitor CLI Commands: The Practical Guide (2026)',
    description:
      'Every Capacitor CLI command you actually use — add, sync, copy, update, run, open, doctor — what each does, when to run it, and how the OtaKit CLI fits alongside for live updates.',
    category: 'Guides',
    publishedAt: '2026-07-17',
    readingTime: '9 min read',
    keywords: [
      'Capacitor CLI commands',
      'npx cap sync',
      'Capacitor cap add',
      'Capacitor cap copy',
      'Capacitor CLI guide',
      'cap doctor',
    ],
    order: 88,
    relatedDocs: [
      { href: '/docs/cli', label: 'CLI reference' },
      { href: '/docs/setup', label: 'Setup' },
      { href: '/docs/ci', label: 'CI automation' },
    ],
  },
  {
    slug: 'upgrade-capacitor-7-to-8',
    title: 'Upgrading from Capacitor 7 to Capacitor 8',
    seoTitle: 'Upgrade Capacitor 7 to 8: Migration Guide (2026)',
    description:
      'A step-by-step guide to upgrading a project from Capacitor 7 to Capacitor 8 — dependency bumps, native project changes, breaking changes to watch, and keeping your OTA runtime version in sync.',
    category: 'Migration',
    publishedAt: '2026-07-17',
    readingTime: '9 min read',
    keywords: [
      'upgrade Capacitor 8',
      'Capacitor 7 to 8',
      'Capacitor 8 migration',
      'Capacitor 8 breaking changes',
      'update Capacitor version',
      'Capacitor 8 upgrade guide',
    ],
    order: 89,
    relatedDocs: [
      { href: '/docs/setup', label: 'Setup' },
      { href: '/docs/channels', label: 'Channels & runtime version' },
      { href: '/docs/cli', label: 'CLI reference' },
    ],
  },
  {
    slug: 'does-apple-allow-live-updates',
    title: 'Does Apple allow live updates without App Store review?',
    seoTitle: 'Does Apple Allow Live Updates Without Review? (2026)',
    description:
      'The direct answer, quoted from Apple’s own guidelines: yes, within limits. What guideline 2.5.2 permits for over-the-air updates, how Apple enforces the line, and how to stay compliant with Capacitor.',
    category: 'Compliance',
    publishedAt: '2026-07-18',
    readingTime: '9 min read',
    keywords: [
      'does Apple allow live updates',
      'Apple live updates without review',
      'guideline 2.5.2',
      'App Store OTA allowed',
      'Apple OTA policy',
      'live updates App Store legal',
    ],
    order: 90,
    relatedDocs: [
      { href: '/docs/update-strategies', label: 'Update strategies' },
      { href: '/docs/security', label: 'Security' },
      { href: '/docs/setup', label: 'Setup' },
    ],
  },
  {
    slug: 'does-google-allow-live-updates',
    title: 'Does Google allow live updates without Play review?',
    seoTitle: 'Does Google Allow Live Updates Without Review? (2026)',
    description:
      "The direct answer for Android: yes, for interpreted web-layer code. What Google Play's Device and Network Abuse policy actually restricts, and how Capacitor OTA updates stay inside it.",
    category: 'Compliance',
    publishedAt: '2026-07-18',
    readingTime: '8 min read',
    keywords: [
      'does Google allow live updates',
      'Google Play live updates',
      'Play Store OTA allowed',
      'device and network abuse policy',
      'Android OTA policy',
      'Google Play update rules',
    ],
    order: 91,
    relatedDocs: [
      { href: '/docs/update-strategies', label: 'Update strategies' },
      { href: '/docs/security', label: 'Security' },
      { href: '/docs/setup', label: 'Setup' },
    ],
  },
  {
    slug: 'bypass-app-store-review-capacitor',
    title: 'How to bypass App Store review for Capacitor app updates',
    seoTitle: 'How to Bypass App Store Review for Updates (2026)',
    description:
      'You can update a Capacitor app without waiting for another App Store or Play review — legitimately. How over-the-air updates let you bypass the store review queue for web-layer changes, and where the line is.',
    category: 'Compliance',
    publishedAt: '2026-07-18',
    readingTime: '9 min read',
    keywords: [
      'bypass app store review',
      'update app without store review',
      'skip App Store review',
      'no store review update',
      'bypass Play Store review',
      'Capacitor update without review',
    ],
    order: 92,
    featured: true,
    relatedDocs: [
      { href: '/docs/update-strategies', label: 'Update strategies' },
      { href: '/docs/setup', label: 'Setup' },
      { href: '/docs/security', label: 'Security' },
    ],
  },
  {
    slug: 'capacitor-ota-use-cases',
    title: 'Capacitor OTA updates: real use cases',
    seoTitle: 'Capacitor OTA Update Use Cases That Matter (2026)',
    description:
      'Beyond hotfixes: the real ways teams use Capacitor over-the-air updates — emergency fixes, staged rollouts, A/B tests, feature flags, seasonal content, and remote config — with links to how each works.',
    category: 'Guides',
    publishedAt: '2026-07-18',
    readingTime: '9 min read',
    keywords: [
      'OTA update use cases',
      'live update examples',
      'Capacitor OTA scenarios',
      'when to use live updates',
      'over the air update uses',
      'mobile app hotfix use case',
    ],
    order: 93,
    relatedDocs: [
      { href: '/docs/update-strategies', label: 'Update strategies' },
      { href: '/docs/channels', label: 'Channels & runtime version' },
      { href: '/docs/setup', label: 'Setup' },
    ],
  },
  {
    slug: 'build-ios-app-from-windows-capacitor',
    title: 'Build an iOS Capacitor app from Windows',
    seoTitle: 'Build an iOS Capacitor App From Windows (2026)',
    description:
      'No Mac? You can still ship a Capacitor iOS app. How to build, sign, and submit an iOS app from a Windows machine using cloud CI runners — and ship every web-layer change after with OtaKit.',
    category: 'Guides',
    publishedAt: '2026-07-19',
    readingTime: '9 min read',
    keywords: [
      'build iOS app on Windows',
      'Capacitor iOS Windows',
      'iOS build without Mac',
      'cloud Mac CI iOS',
      'Windows iOS Capacitor',
      'iOS app no Mac',
    ],
    order: 94,
    relatedDocs: [
      { href: '/docs/ci', label: 'CI automation' },
      { href: '/docs/setup', label: 'Setup' },
      { href: '/docs/cli', label: 'CLI reference' },
    ],
  },
  {
    slug: 'pull-request-preview-builds-capacitor',
    title: 'Turn every pull request into an installable Capacitor preview',
    seoTitle: 'PR Preview Builds for Capacitor Apps (2026)',
    description:
      'Give reviewers a real device build for every pull request. How to publish per-PR preview channels so testers install the exact change on their phone before it merges, with OtaKit and CI.',
    category: 'Guides',
    publishedAt: '2026-07-19',
    readingTime: '8 min read',
    keywords: [
      'PR preview build mobile',
      'pull request preview app',
      'per PR channel Capacitor',
      'preview deploy mobile app',
      'review app on device',
      'Capacitor preview build',
    ],
    order: 95,
    relatedDocs: [
      { href: '/docs/channels', label: 'Channels & runtime version' },
      { href: '/docs/ci', label: 'CI automation' },
      { href: '/docs/cli', label: 'CLI reference' },
    ],
  },
  {
    slug: 'bolt-app-to-ios-android-with-capacitor',
    title: 'Ship your Bolt.new app to iOS and Android with Capacitor',
    seoTitle: 'Bolt.new App to iOS & Android with Capacitor + OTA (2026)',
    description:
      'Built an app with Bolt.new? Export the code, wrap it with Capacitor for the App Store and Google Play, and iterate fast with OtaKit over-the-air updates — no rewrite.',
    category: 'Tutorial',
    publishedAt: '2026-07-19',
    readingTime: '9 min read',
    keywords: [
      'Bolt.new mobile app',
      'Bolt.new to native app',
      'Bolt.new iOS Android',
      'Bolt Capacitor',
      'AI app to app store',
      'Bolt.new live updates',
    ],
    order: 96,
    relatedDocs: [
      { href: '/docs/setup', label: 'Setup' },
      { href: '/docs/react', label: 'React guide' },
      { href: '/docs/cli', label: 'CLI reference' },
    ],
  },
  {
    slug: 'base44-app-to-ios-android-with-capacitor',
    title: 'Ship your Base44 app to iOS and Android with Capacitor',
    seoTitle: 'Base44 App to iOS & Android with Capacitor + OTA (2026)',
    description:
      'Turn a Base44 app into real iOS and Android apps with Capacitor for the stores, then push updates over the air with OtaKit so your AI-built app keeps improving without store delays.',
    category: 'Tutorial',
    publishedAt: '2026-07-19',
    readingTime: '9 min read',
    keywords: [
      'Base44 mobile app',
      'Base44 to native app',
      'Base44 iOS Android',
      'Base44 Capacitor',
      'AI builder to app store',
      'Base44 live updates',
    ],
    order: 97,
    relatedDocs: [
      { href: '/docs/setup', label: 'Setup' },
      { href: '/docs/react', label: 'React guide' },
      { href: '/docs/cli', label: 'CLI reference' },
    ],
  },
  {
    slug: 'astro-to-ios-android-with-capacitor',
    title: 'Convert your Astro site to iOS and Android with Capacitor',
    seoTitle: 'Astro to iOS & Android with Capacitor (+ Live Updates) 2026',
    description:
      'Take an Astro site to native iOS and Android with Capacitor using static output, add device plugins, and ship content and UI changes over the air with OtaKit live updates.',
    category: 'Tutorial',
    publishedAt: '2026-07-20',
    readingTime: '9 min read',
    keywords: [
      'Astro mobile app',
      'Astro Capacitor',
      'Astro to native app',
      'Astro iOS Android',
      'Astro static app',
      'Astro live updates',
    ],
    order: 98,
    relatedDocs: [
      { href: '/docs/setup', label: 'Setup' },
      { href: '/docs/cli', label: 'CLI reference' },
      { href: '/docs/update-strategies', label: 'Update strategies' },
    ],
  },
  {
    slug: 'remix-to-ios-android-with-capacitor',
    title: 'Convert your Remix app to iOS and Android with Capacitor',
    seoTitle: 'Remix to iOS & Android with Capacitor (+ Live Updates) 2026',
    description:
      'Wrap a Remix app as native iOS and Android with Capacitor using SPA mode and static output, then wire up OtaKit to ship JS and CSS changes over the air in minutes.',
    category: 'Tutorial',
    publishedAt: '2026-07-20',
    readingTime: '9 min read',
    keywords: [
      'Remix mobile app',
      'Remix Capacitor',
      'Remix to native app',
      'Remix iOS Android',
      'Remix SPA mode',
      'Remix live updates',
    ],
    order: 99,
    relatedDocs: [
      { href: '/docs/setup', label: 'Setup' },
      { href: '/docs/cli', label: 'CLI reference' },
      { href: '/docs/update-strategies', label: 'Update strategies' },
    ],
  },
  {
    slug: 'capacitor-ai-mobile-apps',
    title: 'Why Capacitor is the best way to ship AI mobile apps',
    seoTitle: 'Capacitor: The Best Way to Ship AI Mobile Apps (2026)',
    description:
      'AI apps change constantly as models, prompts, and UX evolve. Why Capacitor plus over-the-air updates is the fastest stack for shipping and iterating AI mobile apps without waiting on store reviews.',
    category: 'Guides',
    publishedAt: '2026-07-20',
    readingTime: '9 min read',
    keywords: [
      'AI mobile app Capacitor',
      'build AI app mobile',
      'Capacitor AI apps',
      'ship AI app fast',
      'AI app live updates',
      'LLM mobile app',
    ],
    order: 100,
    relatedDocs: [
      { href: '/docs/setup', label: 'Setup' },
      { href: '/docs/react', label: 'React guide' },
      { href: '/docs/update-strategies', label: 'Update strategies' },
    ],
  },
  {
    slug: 'capacitor-changelog-and-release-notes',
    title: 'Changelogs and release notes for Capacitor OTA updates',
    seoTitle: 'Changelogs & Release Notes for Capacitor OTA (2026)',
    description:
      'Store release notes do not cover over-the-air updates. How to manage changelogs for Capacitor OTA releases, surface them in-app when an update applies, and keep users informed of what changed.',
    category: 'Guides',
    publishedAt: '2026-07-20',
    readingTime: '8 min read',
    keywords: [
      'app release notes',
      'changelog mobile app',
      'OTA release notes',
      'Capacitor changelog',
      'in-app whats new',
      'update notes live update',
    ],
    order: 101,
    relatedDocs: [
      { href: '/docs/events', label: 'Events' },
      { href: '/docs/channels', label: 'Channels & runtime version' },
      { href: '/docs/update-strategies', label: 'Update strategies' },
    ],
  },
];

export function getBlogPosts() {
  return [...BLOG_POSTS].sort((a, b) => a.order - b.order);
}

export function getBlogPost(slug: string) {
  return BLOG_POSTS.find((post) => post.slug === slug);
}

/** Build full Next.js metadata (canonical, OG article, Twitter) for a post. */
export function blogPostMetadata(slug: string): Metadata {
  const post = getBlogPost(slug);
  if (!post) return {};

  const url = `${site.url}/blog/${post.slug}`;
  const title = post.seoTitle ?? post.title;

  return {
    title,
    description: post.description,
    keywords: post.keywords,
    alternates: { canonical: url },
    openGraph: {
      title,
      description: post.description,
      url,
      siteName: site.name,
      type: 'article',
      publishedTime: post.publishedAt,
      modifiedTime: post.updatedAt ?? post.publishedAt,
    },
    twitter: {
      card: 'summary_large_image',
      title,
      description: post.description,
    },
  };
}
